//! rubyrs — a tiny Ruby-subset runtime, embeddable in Rust hosts.
//!
//! # Quick start
//!
//! ```no_run
//! use rubyrs::{Runtime, Value};
//!
//! let mut rt = Runtime::new();
//! // Per ADR 0017, `Runtime::new()` defaults its stdout sink to
//! // `std::io::sink()`. Wire it up to wherever the host wants
//! // script output to land before evaluating anything — the CLI
//! // binary uses process stdout; library embedders typically
//! // capture into a buffer.
//! rt.set_stdout(Box::new(std::io::stdout()));
//! rt.eval(r#"puts "hello, world""#, "inline").unwrap();
//!
//! // Register a host function callable from Ruby:
//! rt.register_fn("host_pid", |_args| Ok(Value::Int(std::process::id() as i64)));
//! rt.eval(r#"puts "pid is #{host_pid}""#, "inline").unwrap();
//! ```
//!
//! See [`docs/SUBSET.md`](https://github.com/linyiru/rubyrs/blob/master/docs/SUBSET.md)
//! for the Ruby semantics this runtime does and does not support.

mod ast;
mod bytecode;
mod compiler;
mod error;
mod heap;
mod intern;
#[cfg(feature = "stdlib")]
mod stdlib_vendor;
mod value;
mod vm;

use std::io::Write;
use std::path::Path;
use std::rc::Rc;

pub use error::{RubyError, Span, Trap, TrapFrame};
pub use value::Value;
pub use intern::SymId;
pub use vm::IcStats;

// `_cext_link_keep_alive` — `#[used]` references that keep cext
// ABI symbols alive past the linker DCE pass. See the module's
// own doc comment for the full rationale; gated on `cext`.
#[cfg(feature = "cext")]
mod _cext_link_keep_alive;

// Public Prism node-class manifests. Generated by build.rs from
// `data/supported_prism_nodes.txt` and `data/rides_along_prism_nodes.txt`,
// and validated against `src/ast.rs` — see build.rs. Consumed by
// `rubyrs-gapscan` as the single source of truth for the supported subset.
include!(concat!(env!("OUT_DIR"), "/prism_node_sets.rs"));

/// Configuration for a [`Runtime`]. Defaults are unlimited; tighten for
/// untrusted scripts.
///
/// **Construction**: use `Config::default()` with field-update syntax:
/// ```no_run
/// let _cfg = rubyrs::Config { fuel: Some(1_000_000), ..Default::default() };
/// ```
///
/// Adding new fields is still source-breaking for downstream
/// embedders using full struct literals. The fix is a dedicated
/// builder API (`Config::builder().fuel(n).env(map).build()`)
/// rather than `#[non_exhaustive]`, which forbids struct
/// expressions cross-crate entirely and would have a much larger
/// migration footprint here. Tracked as follow-up; see PR #88
/// thread for the analysis.
pub struct Config {
    /// When true, every potential GC point triggers a full collection.
    /// Useful for catching root-set bugs in host code; rough on
    /// performance. Equivalent to `STRESS_GC=1` env var.
    pub stress_gc: bool,
    /// If `Some(n)`, dispatching more than `n` ops returns a
    /// `ResourceExhausted` trap. Includes ops inside blocks via
    /// `dispatch_until`, so a runaway `[1].each { while true ... }`
    /// cannot bypass the limit.
    pub fuel: Option<u64>,
    /// If `Some(n)`, allocating past `n` simultaneously-live heap
    /// objects (Instance / Array / Hash) returns a `ResourceExhausted`
    /// trap. Checked after `maybe_gc`, so only steady-state allocation
    /// counts.
    ///
    /// **`n` is the cap on the total post-construction live count, not
    /// a per-script-call budget.** The exception-class preamble that
    /// `Runtime::with_config` loads at construction time allocates ~50
    /// HeapObj::Class slots (Exception hierarchy, Object, Comparable,
    /// etc.). Those slots count against `n`. A host that sets
    /// `max_heap_objects: Some(60)` gives user code roughly 10 fresh
    /// allocations before the cap bites, not 60. Set `n` accordingly —
    /// in practice `Some(256)` is a sensible floor for a sandbox that
    /// wants the cap to fire on user-grade misbehaviour rather than
    /// the first `Array.new(20)`.
    pub max_heap_objects: Option<usize>,
    /// If `Some(n)`, pushing past `n` simultaneously-live frames
    /// returns a `ResourceExhausted` trap before the host's Rust stack
    /// can overflow.
    pub max_frames: Option<usize>,
    /// If `Some(n)`, runtime `String#to_sym` (and any other future
    /// script-driven intern path) traps when interning would push
    /// the total beyond `n` distinct symbols. Compile-time intern
    /// (method names, ivar names, string literals in source) is
    /// not capped — it's bounded by source size, which the host
    /// already controls by how big a script it feeds `eval`.
    /// Defends against `arr.map { |x| x.to_s.to_sym }`-style loops
    /// that fuel can't usefully bound.
    pub max_symbols: Option<usize>,
    /// If `Some(n)`, individual `String` / `Array` / `Hash` values
    /// can't grow past `n` bytes of content. String size is the
    /// byte length; Array/Hash size is `len * size_of::<Value>()`
    /// (or `* size_of::<(Value, Value)>()` for Hash). Checked at
    /// mutation sites: `String#+` / `String#*` / `Array#push` /
    /// `Array#<<` / `Array#[]=` / `Hash#[]=`. Heap-cap caps
    /// *number* of live objects (good against shallow alloc
    /// storms); this caps *individual* object size (good against
    /// `"a" * 10_000_000`, which is one heap object that grabs 10 MB).
    pub max_value_bytes: Option<usize>,
    /// If `Some(d)`, an `eval` call that runs longer than `d`
    /// wall-clock time returns a `ResourceExhausted` trap. Checked
    /// every 1024 ops (cheap and precise enough for the host-side
    /// timeouts this is meant to enforce — request budgets,
    /// gemspec-evaluation guards, similar). The deadline is
    /// per-`eval`: each call re-anchors the clock, so a host can
    /// reuse a Runtime across many short evaluations without each
    /// one inheriting the previous timer.
    pub deadline: Option<std::time::Duration>,
    /// Host-injected ENV map. Closes the ADR 0017 deviation: with
    /// the previous default, `LoadConst("ENV")` populated a Hash
    /// from `std::env::vars()` of the host process — script-visible
    /// non-deterministic value and a capability leak from the host's
    /// environment into untrusted scripts.
    ///
    /// `None` (default) means the script sees an empty `ENV` Hash.
    /// `Some(map)` means script-visible `ENV[k]` resolves against
    /// `map` only. The host explicitly chooses what to expose; the
    /// script never reads the host process directly.
    ///
    /// The CLI binary `rubyrs` sets this from `std::env::vars()` so
    /// `rubyrs script.rb` behaves like CRuby; library/embed users
    /// must opt in explicitly.
    pub env: Option<std::collections::HashMap<String, String>>,
    /// Host-injected PID for the `$$` global. Closes the ADR 0017
    /// deviation: with the previous default, `$$` returned the host
    /// process's PID via `std::process::id()` — script-visible
    /// non-deterministic value.
    ///
    /// `None` (default) means `$$` returns `0` as a sentinel
    /// (CRuby's `$$` is documented to always be a positive Integer;
    /// `0` is a sentinel that won't collide with any real PID).
    /// `Some(n)` means `$$` returns `n`.
    ///
    /// Typed as `Option<NonZeroU32>` to match `std::process::id()`'s
    /// return type and enforce the "positive PID" contract at the
    /// type level — `0` is reserved for the default sentinel and
    /// negatives are impossible by construction (Copilot review PR #88).
    ///
    /// The CLI binary `rubyrs` sets this from `std::process::id()`
    /// so `rubyrs script.rb` behaves like CRuby; embed users that
    /// want the host PID exposed must opt in.
    pub pid: Option<std::num::NonZeroU32>,
    /// Host-injected wall-clock source for `Time.now`. Closes the
    /// ADR 0017 deviation that would otherwise let `Time.now`
    /// reach for `std::time::SystemTime::now()` directly —
    /// script-visible non-determinism + a host-clock capability
    /// leak into untrusted scripts.
    ///
    /// `None` (default) means script-visible `Time.now` raises
    /// `RuntimeError` (Tier 1 stays deterministic by default).
    /// `Some(closure)` is called once per `Time.now` invocation;
    /// the closure returns `(epoch_seconds, nanoseconds)` and the
    /// preamble's `Time` class wraps that into a `Value::Object`
    /// instance carrying `@sec` / `@nsec` ivars.
    ///
    /// The closure is `Arc<dyn Fn>` so a single Runtime can be
    /// shared across calls without consuming the injected source.
    /// `Send + Sync` keeps the Runtime usable from multi-threaded
    /// host code that wraps it in an `Arc<Mutex<_>>`-style guard;
    /// rubyrs itself is single-threaded (one Runtime = one Vm at
    /// a time), but the bound matches what `register_fn` already
    /// requires of host functions.
    ///
    /// The CLI binary `rubyrs` injects `std::time::SystemTime::now()`
    /// so `rubyrs script.rb` behaves like CRuby; library / embed
    /// users that want the host wall-clock exposed must opt in
    /// explicitly. Deterministic-test hosts inject a fixed
    /// `|| (1_700_000_000, 0)` closure for reproducible output.
    pub time_now: Option<std::sync::Arc<dyn Fn() -> (i64, u32) + Send + Sync>>,
}

impl Default for Config {
    /// Default Config. `stress_gc` auto-enables from the `STRESS_GC`
    /// env var on non-wasi hosts so `STRESS_GC=1 cargo test` flips
    /// every `Runtime::new()`-using test into stress mode — the
    /// previous behavior, lost when `Vm::new` stopped reading the
    /// env var to satisfy wizer's no-imports rule. The wizer path
    /// does NOT go through `Config::default()` (it calls
    /// `Runtime::new_default_impl` directly), so this env read can't
    /// pollute the snapshot. The CLI binary explicitly reads
    /// `STRESS_GC` again from main.rs for the same flag — both reads
    /// agree, harmless.
    fn default() -> Self {
        #[cfg(not(target_os = "wasi"))]
        let stress_gc = std::env::var("STRESS_GC").is_ok();
        #[cfg(target_os = "wasi")]
        let stress_gc = false;
        Self {
            stress_gc,
            fuel: None,
            max_heap_objects: None,
            max_frames: None,
            max_symbols: None,
            max_value_bytes: None,
            deadline: None,
            env: None,
            pid: None,
            time_now: None,
        }
    }
}

/// Read-only handle into the runtime's heap, passed to closures
/// registered via [`Runtime::register_fn_v2`]. Lets the closure
/// unpack `Value::Array` / `Value::Hash` arguments without going
/// back through [`Runtime::resolve_array`] / [`Runtime::resolve_hash`]
/// (which clone).
///
/// Mutability is omitted by construction:
/// - `HostCtx` exposes no mutating method.
/// - The V2 dispatch path (see `Vm::invoke_host_fn`) does NOT
///   overwrite `CURRENT_VM_PTR`, and the TLS itself is `pub(crate)`,
///   so an external v2 closure has no language-level path to reach
///   the `*mut Vm` re-entry channel. The TLS may already be non-null
///   from an outer v1/cext frame — the guarantee is "unreachable
///   from external v2 code," not "TLS is null."
///
/// Together these mean the slices returned by `resolve_array` /
/// `resolve_hash` are valid for the entire closure body without
/// further caveat from outside the crate. Embed hosts MUST NOT leak
/// the returned slices past the closure return (the lifetime
/// already prevents this, but worth stating).
pub struct HostCtx<'a> {
    heap: &'a heap::Heap,
    interner: &'a intern::Interner,
}

impl<'a> HostCtx<'a> {
    /// Internal constructor — the dispatch site borrows `&Heap` and
    /// `&Interner` from the VM and hands them to the v2 closure via
    /// this ctx. Both borrows are immutable and time-bounded by the
    /// closure invocation (see `Vm::invoke_host_fn`).
    pub(crate) fn new(heap: &'a heap::Heap, interner: &'a intern::Interner) -> Self {
        Self { heap, interner }
    }

    /// Borrow the contents of a `Value::Array`. Returns `None` for
    /// any other shape — the host fn can decide whether to error or
    /// fall through.
    pub fn resolve_array(&self, val: &Value) -> Option<&[Value]> {
        if let Value::Array(id) = val {
            Some(self.heap.array(*id).as_slice())
        } else {
            None
        }
    }

    /// Borrow the contents of a `Value::Hash` as a flat slice of
    /// `(key, value)` pairs (preserving insertion order). Returns
    /// `None` for any other shape.
    pub fn resolve_hash(&self, val: &Value) -> Option<&[(Value, Value)]> {
        if let Value::Hash(id) = val {
            Some(self.heap.hash(*id).as_slice())
        } else {
            None
        }
    }

    /// Borrow the interned name of a `Value::Sym`. Returns `None` for
    /// any other shape. Useful for v2 host fns that receive a
    /// kwargs `Hash` with Symbol keys (`require:`, `platforms:`, …)
    /// — the host can branch on the borrowed `&str` directly without
    /// a Ruby-side `k.to_s` rebuild of the Hash.
    pub fn resolve_sym(&self, val: &Value) -> Option<&str> {
        if let Value::Sym(id) = val {
            Some(self.interner.resolve(*id))
        } else {
            None
        }
    }
}

/// A self-contained rubyrs runtime. State (class definitions, top-level
/// methods, registered host functions, GC heap) persists across calls to
/// [`Runtime::eval`].
///
/// Embedders that want per-call isolation without paying the preamble
/// load cost on every Runtime construction (~3–6 ms) can construct one
/// Runtime and call [`Runtime::reset`] between evals — that wipes
/// user-introduced state (globals, user classes / constants / methods,
/// heap allocations, interned-at-eval symbols) but keeps everything the
/// preamble set up.
pub struct Runtime {
    vm: vm::Vm,
    /// Per-`eval` wall-clock budget (P2-14a). Retained as a
    /// Duration; an absolute `Instant` is computed at the start of
    /// each `eval` call and stored on `Vm.deadline_at`. `None` means
    /// unlimited.
    deadline: Option<std::time::Duration>,
    /// Snapshot of post-preamble state, captured by `with_config`
    /// (and the wizer-path constructor) once `load_preamble`
    /// completes and resource caps have been restored. `reset()`
    /// uses this snapshot to identify which heap slots / interned
    /// symbols / classes / constants / methods were preamble-
    /// originated (preserve) vs added by user `eval()` (clear).
    ///
    /// `None` only during the brief window inside `with_config`
    /// before the snapshot is taken; `Some(_)` for the rest of
    /// the Runtime's lifetime. `reset()` is a no-op when None.
    post_preamble: Option<PostPreambleSnapshot>,
}

/// Captures the boundary between "preamble state" and "user state"
/// at the moment preamble finishes loading. `reset()` rewinds the
/// Runtime to this exact baseline.
///
/// The snapshot stores the post-preamble **values** of mutable
/// per-class method tables, top-level constants, and top-level
/// methods — not just the keys — so that user code that
/// **redefines** a preamble method or constant (e.g. `class String;
/// def length; 999; end; end` or `Exception = 1`) is fully
/// rewound on reset, not just left in place when the key happens
/// to match. Storing values instead of keys roughly 10×s the
/// snapshot's memory footprint (~few hundred KB total — still
/// dwarfed by everything else in a live Runtime) but is the only
/// way to honour the documented "rewind to exact post-preamble
/// state" contract.
struct PostPreambleSnapshot {
    /// `vm.heap.slots.len()` at preamble completion. `reset()`
    /// truncates the heap back to this length.
    heap_slot_count: usize,
    /// `vm.heap.live_count` at preamble completion. `reset()`
    /// restores live_count to this value.
    heap_live_count: usize,
    /// `vm.interner.len()` at preamble completion. `reset()`
    /// truncates `interner.vec` and drains stale `interner.map`
    /// entries — but ONLY down to `max(interner_len,
    /// host_fn_max_sym + 1)` (see the reset implementation), so
    /// any SymId referenced by `host_fns` registered *after*
    /// construction stays valid.
    interner_len: usize,
    /// `vm.classes` HashMap as it was at preamble completion.
    /// `reset()` clones this and assigns to `vm.classes`,
    /// preserving every preamble class object identity (Rc clone)
    /// and erasing any user `class X; end` definitions.
    classes: std::collections::HashMap<intern::SymId, std::rc::Rc<value::Class>>,
    /// `vm.constants` as of preamble completion. `reset()` clones
    /// and replaces. Catches the case where user code redefines a
    /// preamble constant (e.g. `Exception = 1`) — the snapshot's
    /// original Class value is restored, not just left.
    constants: std::collections::HashMap<intern::SymId, value::Value>,
    /// `vm.toplevel_methods` as of preamble completion.
    /// Restored by clone-and-replace so a user `def foo; ...` —
    /// or a redefinition of a preamble-supplied toplevel method —
    /// fully rewinds.
    toplevel_methods: std::collections::HashMap<intern::SymId, std::rc::Rc<value::Method>>,
    /// For every preamble class, the method table snapshot. The
    /// outer key is the class's name SymId; the inner map is the
    /// `methods` HashMap as it was at preamble completion. On
    /// `reset()`, each preserved preamble class has its `methods`
    /// `RefCell` overwritten with a clone of this map.
    ///
    /// Same value-not-key reason: a user `class String; def
    /// length; 999; end; end` would silently survive a key-only
    /// snapshot because `length` is a preamble String method —
    /// the value-snapshot restores the preamble's original
    /// `Method` so the override is gone post-reset.
    class_methods:
        std::collections::HashMap<intern::SymId, std::collections::HashMap<intern::SymId, std::rc::Rc<value::Method>>>,
}

/// Per-process slot used by the wizer pre-initialize path. On
/// wasm32-wasip1, the binary exports `wizer.initialize` (below)
/// which constructs a default Runtime and stashes it here; Wizer
/// then snapshots linear memory so a later `wasmtime run` picks
/// up the prebuilt classes + preamble bytecode without redoing
/// that work. The CLI binary's `main()` calls `take_wizer_runtime()`
/// to consume the slot.
///
/// Single-threaded by design: wasm32-wasip1 has no threads, and
/// the CLI binary owns the process. Embedded hosts that link
/// rubyrs as a library don't touch this slot — they construct
/// their own Runtime via `Runtime::new()` / `Runtime::with_config()`.
#[cfg(target_os = "wasi")]
static mut WIZER_RUNTIME: Option<Runtime> = None;

/// Wizer entry point. Builds a default-Config Runtime (registers
/// builtin classes, runs the Ruby preamble) and stashes it in
/// `WIZER_RUNTIME` for the eventual `main()` to consume.
///
/// Wizer's rules forbid imported function calls during init, so
/// we deliberately split out `new_default_impl()` (no env reads,
/// no PID lookup, no stdout binding) as the wizer-able subset.
/// Config-driven settings — fuel caps, env override, deadline —
/// are applied later by `main()` via `apply_config()`, AFTER the
/// snapshot.
///
/// If Wizer is never invoked, the function is dead code; the
/// `#[export_name]` attribute keeps it linked anyway so the
/// build artifact is wizer-ready as-shipped.
#[cfg(target_os = "wasi")]
#[unsafe(export_name = "wizer.initialize")]
pub extern "C" fn wizer_initialize() {
    // SAFETY: wasm32-wasip1 is single-threaded; this static is
    // only mutated here (during the one wizer-init pass) and
    // consumed once by `take_wizer_runtime()` from main(). Use
    // `addr_of_mut!` + `(*p).replace(...)` to avoid the Rust
    // 2024 `static_mut_refs` lint AND ensure any prior occupant
    // is dropped (a bare `p.write(...)` would leak the previous
    // Runtime if `wizer.initialize` were somehow invoked more
    // than once during a debugging / embedding cycle).
    unsafe {
        let p = std::ptr::addr_of_mut!(WIZER_RUNTIME);
        let _prev = (*p).replace(Runtime::new_default_impl());
        // `_prev` (Option<Runtime>) drops here, freeing the
        // earlier Runtime's heap + Vm slots if one existed.
    }
}

/// Consume the wizer-built Runtime if one is present, returning
/// `None` when the binary wasn't put through wizer. The CLI
/// binary's `main()` calls this, then applies its own Config
/// (env vars, PID, fuel) on top of the rehydrated state.
#[cfg(target_os = "wasi")]
pub fn take_wizer_runtime() -> Option<Runtime> {
    // SAFETY: same single-threaded justification as above; this
    // is the unique consumer site. `addr_of_mut!` for the same
    // 2024-edition reason as `wizer_initialize`.
    unsafe {
        let p = std::ptr::addr_of_mut!(WIZER_RUNTIME);
        (*p).take()
    }
}

/// Snapshot of every Runtime field the preamble-bootstrap path
/// must lift before running `load_preamble` and restore after.
/// Bundling them into one type means "add a new resource cap"
/// touches exactly one struct (plus its `take_from` / `restore_to`
/// pair); previous shape had six paired `.take()` + restore lines
/// in `with_config`, easy to forget half of on a new cap.
///
/// Every field here is either an `Option<primitive>` (Copy) or
/// `bool`, so the guard can restore by `&self` reference without
/// moving anything out of itself in `Drop`.
#[derive(Default)]
struct ResourceCaps {
    fuel: Option<u64>,
    max_frames: Option<usize>,
    max_symbols: Option<usize>,
    max_value_bytes: Option<usize>,
    max_live: Option<usize>,
    deadline: Option<std::time::Duration>,
    // `stress_gc` is treated as a cap here even though it isn't a
    // resource budget — it makes GC fire on every potential point,
    // ballooning preamble cost ~10× when on. Lifting it during
    // preamble keeps Runtime construction time observably
    // independent of the host's stress_gc choice.
    stress_gc: bool,
}

impl ResourceCaps {
    /// Take caps off the Runtime + Vm, leaving zero/None in place.
    /// Subsequent eval()s run unbounded until the caps are
    /// restored.
    fn take_from(rt: &mut Runtime) -> Self {
        ResourceCaps {
            fuel: rt.vm.fuel.take(),
            max_frames: rt.vm.max_frames.take(),
            max_symbols: rt.vm.max_symbols.take(),
            max_value_bytes: rt.vm.max_value_bytes.take(),
            max_live: rt.vm.heap.max_live.take(),
            deadline: rt.deadline.take(),
            stress_gc: std::mem::replace(&mut rt.vm.stress_gc, false),
        }
    }

    /// Restore the captured caps. Takes `&self` because every
    /// field is Copy / bool, so `Drop` can call this through the
    /// guard's reference without moving out.
    fn restore_to(&self, rt: &mut Runtime) {
        rt.vm.fuel = self.fuel;
        rt.vm.max_frames = self.max_frames;
        rt.vm.max_symbols = self.max_symbols;
        rt.vm.max_value_bytes = self.max_value_bytes;
        rt.vm.heap.max_live = self.max_live;
        rt.deadline = self.deadline;
        rt.vm.stress_gc = self.stress_gc;
    }
}

/// RAII guard that lifts ResourceCaps off a Runtime for as long
/// as it exists in scope, and restores them on Drop — including
/// the unwinding path if `load_preamble` (or anything else inside
/// the guarded scope) Rust-panics. Without this, a host that
/// catches the unwind via `catch_unwind` could recover a Runtime
/// with all caps silently zeroed, defeating the very sandbox
/// they configured.
struct CapsGuard<'a> {
    rt: &'a mut Runtime,
    saved: ResourceCaps,
}

impl<'a> CapsGuard<'a> {
    fn lift(rt: &'a mut Runtime) -> Self {
        let saved = ResourceCaps::take_from(rt);
        CapsGuard { rt, saved }
    }
}

impl Drop for CapsGuard<'_> {
    fn drop(&mut self) {
        self.saved.restore_to(self.rt);
    }
}

impl PostPreambleSnapshot {
    /// Capture the post-preamble baseline from a freshly-constructed
    /// Runtime. Called once at the end of `with_config` /
    /// `new_default_impl`; the resulting snapshot is the target
    /// state every subsequent `reset()` rewinds to.
    fn capture(rt: &Runtime) -> Self {
        let class_methods = rt
            .vm
            .classes
            .iter()
            .map(|(name, cls)| (*name, cls.methods.borrow().clone()))
            .collect();
        PostPreambleSnapshot {
            heap_slot_count: rt.vm.heap.slots.len(),
            heap_live_count: rt.vm.heap.live_count,
            interner_len: rt.vm.interner.len(),
            classes: rt.vm.classes.clone(),
            constants: rt.vm.constants.clone(),
            toplevel_methods: rt.vm.toplevel_methods.clone(),
            class_methods,
        }
    }
}

impl Runtime {
    pub fn new() -> Self {
        Self::with_config(Config::default())
    }

    pub fn with_config(cfg: Config) -> Self {
        // Apply Config BEFORE the preamble so host-visible
        // settings (`env`, `pid`, `time_now`) the preamble might
        // consult use the host's values, and `apply_config`'s
        // contract ("call before any eval()") is honored. The
        // wizer path can't do this: it has no host Config at
        // snapshot time, so its preamble runs under defaults —
        // that's by design and documented on `new_default_impl`.
        //
        // Then lift the resource caps + `stress_gc` for the
        // duration of preamble load. The preamble is internal
        // infrastructure, not user code; consuming the host's
        // resource budget for bootstrap means a host that wants a
        // tight sandbox (fuzz, untrusted-script eval) cannot
        // construct a Runtime at all — the preamble traps and
        // `.expect` in `load_preamble` panics with SIGABRT instead
        // of returning a recoverable error. Originally surfaced
        // by the cargo-fuzz harness in PR #180 with a magic
        // `fuel: Some(50_000)` workaround.
        //
        // The `CapsGuard` is RAII: on every exit path from this
        // scope (normal return AND panic unwinding), the saved
        // caps are restored. A panic mid-preamble that an
        // embedder catches via `catch_unwind` therefore yields a
        // Runtime with its sandbox intact, not silently disarmed.
        let mut rt = Self::build_skeleton();
        rt.apply_config(cfg);
        {
            let guard = CapsGuard::lift(&mut rt);
            guard.rt.load_preamble();
            // guard drops here; caps restored.
        }
        rt.post_preamble = Some(PostPreambleSnapshot::capture(&rt));
        rt
    }

    /// Construct a Runtime skeleton (fresh Vm, no preamble) shared
    /// by `with_config` and the wizer pre-initialize path. Doing it
    /// this way lets the non-wizer constructor apply Config before
    /// the preamble runs, while the wizer path runs the preamble
    /// under defaults so the snapshot is host-Config-independent.
    fn build_skeleton() -> Self {
        // PR #60 review #14: clear any leftover per-thread cext
        // STATE before constructing a fresh Vm. The persistent
        // CExtState (L3-H) lives in a thread_local; without this
        // reset, a previous Runtime's `values` table — which can
        // hold `CValue::HeapRef(ObjId)` referencing the OLD Vm's
        // heap — would dangle into the new Vm and resolve to
        // unrelated objects (or panic on out-of-range ObjId).
        #[cfg(all(feature = "cext", not(target_os = "wasi")))]
        rubyrs_cext::reset_state();

        let interner = intern::Interner::new();
        let vm = vm::Vm::new(vec![], interner);
        Runtime { vm, deadline: None, post_preamble: None }
    }

    /// Wizer-able default Runtime: skeleton + preamble, no host
    /// Config applied. The wizer path stashes this in
    /// `WIZER_RUNTIME`; `main()` later calls `apply_config()` on the
    /// rehydrated instance to layer host-driven settings (env, PID,
    /// fuel caps) on top. The preamble runs under default caps here
    /// — fuel/stress_gc/etc. do NOT apply to preamble execution in
    /// the wizer path (they can't: wizer's no-imports rule forbids
    /// reading host env at snapshot time).
    #[cfg(target_os = "wasi")]
    fn new_default_impl() -> Self {
        let mut rt = Self::build_skeleton();
        rt.load_preamble();
        rt.post_preamble = Some(PostPreambleSnapshot::capture(&rt));
        rt
    }

    /// Apply a Config to an already-constructed Runtime. Used by the
    /// wizer-init path so the snapshotted Runtime (built with default
    /// Config) can pick up host-driven settings (env vars, PID, fuel
    /// caps) at runtime AFTER wizer rehydrates it.
    ///
    /// Contract: call this once, BEFORE any `eval()` or `ENV` access.
    /// Later calls fully overwrite resource caps, PID, deadline, and
    /// `stress_gc`. However, `cfg.env` is consumed lazily on the
    /// first `ENV` materialization inside the Vm (via
    /// `env_override.take()`); once `ENV` has been touched by Ruby
    /// code, a subsequent `apply_config` cannot retroactively change
    /// the script-visible env. The CLI binary always calls this
    /// exactly once at startup, so the caveat only matters for
    /// embedders.
    pub fn apply_config(&mut self, cfg: Config) {
        // Fully overwrite (not OR-merge) so a later call with
        // `stress_gc: false` actually clears a previously-set true.
        // Previously this was `if cfg.stress_gc { ... = true; }`,
        // which made the flag monotonic and broke the documented
        // overwrite semantics.
        self.vm.stress_gc = cfg.stress_gc;
        self.vm.fuel = cfg.fuel;
        self.vm.max_frames = cfg.max_frames;
        self.vm.heap.max_live = cfg.max_heap_objects;
        self.vm.max_symbols = cfg.max_symbols;
        self.vm.max_value_bytes = cfg.max_value_bytes;
        self.vm.env_override = cfg.env;
        self.vm.pid = cfg.pid.map(|n| n.get() as i64);
        self.vm.time_now = cfg.time_now;
        self.deadline = cfg.deadline;
    }

    /// Rewind the Runtime to its post-preamble state — every class,
    /// constant, method, heap slot, and interned symbol introduced
    /// by user `eval()` calls is discarded; everything the preamble
    /// set up is preserved.
    ///
    /// Intended for embedders that want per-call isolation without
    /// paying ~3–6 ms of preamble re-load per Runtime. Construct
    /// once via [`Runtime::with_config`], then call `reset()` between
    /// inputs:
    ///
    /// ```no_run
    /// # use rubyrs::{Config, Runtime};
    /// let mut rt = Runtime::with_config(Config::default());
    /// for input in ["1+1", "puts :hi", "[1,2,3].map { |x| x*2 }"] {
    ///     rt.reset();
    ///     let _ = rt.eval(input, "fuzz.rb");
    /// }
    /// ```
    ///
    /// What's preserved:
    /// - Class hierarchy + method tables created by the preamble
    ///   (Exception, StandardError, Object, Comparable, String,
    ///   Integer, Array, Hash, ...).
    /// - Toplevel methods / constants the preamble installed.
    /// - Compiled bytecode (`vm.protos`) and host-registered
    ///   functions (`vm.host_fns`).
    /// - Resource caps (`Config::fuel`, `max_frames`, ...) and host
    ///   state (`env`, `pid`, `time_now`, `stress_gc`, `stdout`).
    /// - Pre-interned hot SymIds (`sym_to_s`, etc.) and the literal
    ///   caches (`regex_cache`, `bigint_lit_cache`) — those keys
    ///   were interned by the compiler, not by user code.
    ///
    /// What's cleared:
    /// - Heap slots allocated after the preamble (user instances,
    ///   Arrays, Hashes, ...).
    /// - Interner entries past the preamble high-water (user
    ///   `String#to_sym`, user method-name interning, ...).
    /// - User-defined classes, constants, toplevel methods.
    /// - User-added methods on preamble classes (e.g. `class
    ///   String; def foo; ...; end; end` does NOT leak into the
    ///   next eval).
    /// - Globals (`$gvars`), toplevel cvars (`@@x`), `$~` /
    ///   `last_match`, lazily-built `ENV` hash, `loaded_features`.
    /// - Control-flow signals from a possibly-trapped prior eval:
    ///   `break_signaled`, `method_return`, `pending_loop_transfer`,
    ///   `class_stack`, residual `stack` / `frames` / `pinned`.
    ///
    /// **Important:** any `ObjId` or `SymId` value the host
    /// captured from a prior `eval()` is invalid after `reset()` —
    /// it points into truncated storage. Hosts that retain such
    /// values across resets are responsible for not dereferencing
    /// them (the fuzz / per-request use case discards user code
    /// between resets, so this is a non-concern for them).
    ///
    /// **No-op** if the Runtime hasn't completed `with_config`'s
    /// construction yet (no snapshot was taken). Cheap to call
    /// repeatedly; per-reset cost is dominated by the heap +
    /// interner truncations, both `O(removed_entries)`.
    pub fn reset(&mut self) {
        let Some(snapshot) = self.post_preamble.as_ref() else {
            return;
        };
        // --- Heap: truncate user-allocated slots ---
        // `Vec::truncate` is O(removed) and drops the HeapObj enum
        // variants (including their Rc<...> inner data), releasing
        // their ref counts. Any preamble-allocated slots beyond
        // the high-water mark would also be released — by
        // definition there are none, since the snapshot captures
        // `slots.len()` immediately after preamble.
        self.vm.heap.slots.truncate(snapshot.heap_slot_count);
        self.vm.heap.marks.truncate(snapshot.heap_slot_count);
        // `free` is the GC-reclaimed-slot index list. Any entries
        // beyond the high-water are now out of range; entries
        // below are still valid preamble-era slots that were
        // freed pre-snapshot (none exist in practice, but clearing
        // is safer than asserting empty).
        self.vm.heap.free.retain(|&idx| (idx as usize) < snapshot.heap_slot_count);
        self.vm.heap.live_count = snapshot.heap_live_count;
        // --- Interner: drop user-interned symbols, but never
        //     truncate past any SymId referenced by `host_fns`. ---
        // `register_fn` interns the function name AFTER
        // `with_config` returns (i.e. post-snapshot). Those
        // SymIds are above `snapshot.interner_len`. Naive
        // truncation back to the snapshot length would leave
        // `host_fns` keyed by now-invalid SymIds — and the next
        // user-interned string would silently reuse those IDs,
        // dispatching to the wrong host fn (or panicking on
        // `interner.resolve(...)`).
        //
        // Compute the post-truncation length as `max(snapshot_len,
        // max_host_fn_sym + 1)`. User-interned symbols that
        // happen to fall below this floor get preserved as a
        // small leak — acceptable trade-off for never corrupting
        // host-fn dispatch.
        let host_fn_max = self
            .vm
            .host_fns
            .keys()
            .map(|sym| sym.0 as usize)
            .max();
        let keep_len = match host_fn_max {
            Some(m) => snapshot.interner_len.max(m + 1),
            None => snapshot.interner_len,
        };
        self.vm.interner.truncate_to(keep_len);
        // --- Restore classes / constants / toplevel methods by
        //     value (not just key-filter). User code that
        //     REDEFINES a preamble class / constant / method
        //     (`Exception = 1`, `class String; def length; 999;
        //     end; end`, etc.) overwrites the value in place; a
        //     key-only `retain` would happily leave the user's
        //     redefinition because the SymId is still in the
        //     snapshot's keyset. Clone-and-replace is the only
        //     way to fully rewind.
        //
        // Rc<Class> / Rc<Method> / Value::Str(Rc<...>) all clone
        // by refcount bump, so the actual cost is HashMap copies
        // (~hundreds of entries; sub-microsecond).
        self.vm.classes = snapshot.classes.clone();
        self.vm.constants = snapshot.constants.clone();
        self.vm.toplevel_methods = snapshot.toplevel_methods.clone();
        // --- Per-class method tables: replace each preamble
        //     class's `methods` RefCell content with the
        //     snapshot's copy. Catches BOTH user-added methods
        //     on preamble classes AND user-redefined preamble
        //     methods (`class String; def length; ...; end; end`
        //     — `length` is a preamble String method, so a
        //     key-retain would leave the override in place). ---
        for (cls_name, cls) in &self.vm.classes {
            if let Some(snap_methods) = snapshot.class_methods.get(cls_name) {
                *cls.methods.borrow_mut() = snap_methods.clone();
            }
        }
        // --- Literal caches keyed by user-time SymIds: clear. ---
        // `regex_cache` and `bigint_lit_cache` map compile-time-
        // interned SymIds to compiled regex / parsed BigInt
        // values. Their keys are the SymIds of the literal
        // SOURCE TEXT — keys assigned by the user-eval's
        // compiler. After `reset()`'s interner truncation, the
        // same SymId values can be reused for entirely different
        // literal strings in the next eval, which would silently
        // return the wrong cached value.
        //
        // Wholesale-clear instead of trying to filter by key.
        // The caches re-populate cheaply on the next use (one
        // `regex::Regex::new` call per pattern).
        #[cfg(feature = "regex")]
        {
            self.vm.regex_cache.clear();
        }
        #[cfg(feature = "bignum")]
        {
            self.vm.bigint_lit_cache.clear();
        }
        // --- Volatile per-eval state: reset to empty. ---
        self.vm.stack.clear();
        self.vm.frames.clear();
        self.vm.pinned.clear();
        self.vm.globals.clear();
        self.vm.toplevel_cvars.clear();
        self.vm.class_stack.clear();
        self.vm.class_visibility_stack.clear();
        #[cfg(feature = "regex")]
        {
            self.vm.last_match = None;
        }
        self.vm.env_hash = None;
        #[cfg(not(target_os = "wasi"))]
        {
            self.vm.loaded_features.clear();
            self.vm.loaded_stdlib_stubs.clear();
        }
        // Control-flow signals from a possibly-trapped prior eval.
        // Without these, a user script that broke out of a loop
        // (Op::Break) and then trapped would leave
        // `break_signaled = true`; the next eval's iterators would
        // see a stale break signal.
        self.vm.break_signaled = false;
        self.vm.method_return = None;
        self.vm.pending_loop_transfer = None;
        self.vm.suppress_call_result_push = false;
        self.vm.bypass_visibility_once = false;
        // `op_counter` is per-eval; `deadline_at` is set per-eval.
        // Both reset by `eval()`'s preamble anyway, but clear here
        // too so a `reset()` between user evals leaves no trail.
        self.vm.op_counter = 0;
        self.vm.deadline_at = None;
        // Bump `method_gen` so any stale `CallCache` entries
        // pointing at user-defined methods removed above
        // invalidate on next lookup. `CallCache` re-checks
        // `method_gen` per hit; no need to clear the slots
        // themselves.
        self.vm.method_gen = self.vm.method_gen.wrapping_add(1);
    }

    // Internal-only inspectors: let integration tests in
    // `tests/embed/reset.rs` assert on `vm.heap.live_count` and
    // `vm.interner.len()` without making those fields part of the
    // stable Runtime API.
    //
    // These are `pub fn` rather than `#[cfg(test)]`-gated because
    // integration tests live in a separate compilation unit from
    // the lib crate, and `#[cfg(test)]` doesn't apply to that
    // unit. The `__test_` prefix + `#[doc(hidden)]` is the de-facto
    // Rust convention for "internal, no stability guarantee — do
    // not call from production code." If we later want a
    // hard-enforced gate, a `test-internals` Cargo feature would
    // work, but it'd require every test invocation to pass
    // `--features test-internals`, which is more churn than the
    // current convention is worth.
    #[doc(hidden)]
    pub fn __test_vm_live_count(&self) -> usize {
        self.vm.heap.live_count
    }
    #[doc(hidden)]
    pub fn __test_vm_interner_len(&self) -> usize {
        self.vm.interner.len()
    }

    /// Bootstrap the built-in Ruby class hierarchy (currently just
    /// exceptions) by `eval`-ing a small Ruby preamble. Done with the
    /// runtime's own machinery so the resulting classes look identical
    /// to user-defined ones (no special-cased C structs).
    fn load_preamble(&mut self) {
        // Exception hierarchy first — other preamble fragments below
        // (and any user code that raises during their load) need
        // `RuntimeError`/`StandardError`/etc. to be resolvable.
        // Lives in its own file per the random.rb / time.rb pattern:
        // larger, structurally distinct from the class-stub block
        // below, and meaty enough that editor support pays off.
        self.eval(
            include_str!("preamble/exceptions.rb"),
            "<rubyrs:preamble:exceptions>",
        )
            .expect("ICE: failed to load exception preamble");
        // Object — universal ancestor stub. Loaded between
        // exceptions and the remaining preamble (which contains
        // `class X < Object` shapes) so the constant resolves at
        // class-definition time.
        self.eval(
            include_str!("preamble/object.rb"),
            "<rubyrs:preamble:object>",
        )
            .expect("ICE: failed to load Object preamble");
        // Comparable mixin — comparison-operator fan-out from
        // `<=>`. Loaded ahead of the inline PREAMBLE so any
        // `class X < Comparable` shape (or `is_a?(Comparable)`
        // predicate) inside the remaining preamble fragments
        // resolves at definition time.
        self.eval(
            include_str!("preamble/comparable.rb"),
            "<rubyrs:preamble:comparable>",
        )
            .expect("ICE: failed to load Comparable preamble");
        // MatchData — the value returned by `String#match`. Needs
        // to be loaded before any regex match call because the
        // Rust-side `Vm::materialize_match_data` looks the class
        // up by name when allocating the result. Cfg-irrelevant
        // here (regex-off builds simply never call into
        // materialize_match_data, but loading the empty preamble
        // string is cheap).
        self.eval(
            include_str!("preamble/match_data.rb"),
            "<rubyrs:preamble:match_data>",
        )
            .expect("ICE: failed to load MatchData preamble");
        // Mutex — single-threaded no-op shim. Tier 1 has no OS
        // threads, so the entire lock surface degenerates to
        // "run the block / no-op".
        self.eval(
            include_str!("preamble/mutex.rb"),
            "<rubyrs:preamble:mutex>",
        )
            .expect("ICE: failed to load Mutex preamble");
        // Thread — single-threaded Tier 1 stub. Only
        // `Thread.current.object_id` is modeled (tilt uses it to
        // suffix compiled-method names). See preamble/thread.rb
        // for the divergence surface.
        self.eval(
            include_str!("preamble/thread.rb"),
            "<rubyrs:preamble:thread>",
        )
            .expect("ICE: failed to load Thread preamble");
        const PREAMBLE: &str = r#"
## Stub classes for built-in types. Without these, `5.class` and
## friends have nothing to return; the bodies stay empty because
## built-in method dispatch goes through `primitive_call` /
## `collection_call` before any class-table lookup. Re-opening
## these from user code does work (`class Integer; def foo; end`)
## but adding methods that way won't shadow the primitive arms —
## see docs/SUBSET.md.
## `class Object; end` is loaded from `preamble/object.rb` BEFORE
## this `PREAMBLE` eval, so subsequent `class Foo < Object` shapes
## here resolve without ordering hazards.
class Integer
end
class Float
end
class String
end
class Symbol
end
class Array
end
class Hash
end
class Range
end
class TrueClass
end
class FalseClass
end
class NilClass
end
class Proc
end
## Method — `Object#method(:foo)` returns a BoundMethod value
## whose class reports as Method. Stub class so `m.class.name`
## resolves to "Method".
class Method
end
## UnboundMethod — `Method#unbind` returns this; `bind(obj)`
## rehydrates it into a Method.
class UnboundMethod
end
## Module — empty preamble shell so `is_a?(Module)` /
## `class_of` reach a real class table entry. CRuby's
## hierarchy: `Class < Module < Object`; rubyrs mirrors
## the inheritance so `Class.is_a?(Module)` walks
## superclass → Module → true via the existing
## `class_is_a` helper. `module` keyword sets
## `is_module: true` on the Class shell (`Op::DefModule`).
module Module
end
class Class < Module
end
## File — class-method dispatch is wired host-side in
## `Vm::file_class_dispatch`. The class body is intentionally
## empty; methods are not defined here.
class File
end
## `class Mutex; ... end` (single-threaded no-op shim) is loaded
## from `preamble/mutex.rb` BEFORE this `PREAMBLE` eval.
## Kernel — sentinel class (CRuby's Kernel is a Module included in
## Object). We don't model Modules, but real codebases use
## `Kernel.instance_method(:class).bind(scope).call` for a stable
## handle to a method that gets invoked many times later (tilt
## does this at template.rb:238 to cache `:class` once at boot).
## `is_primitive_class_name` lists Kernel so
## `Class#instance_method` synthesises an UnboundMethod, and
## UnboundMethod#bind skips its is-a check when the captured class
## is Kernel — every value is_a Kernel in CRuby semantics, so the
## downstream `do_call` routes the method name to the receiver's
## normal method dispatch as if called directly.
##
## DIVERGENCE: in CRuby, an UnboundMethod captured from Kernel
## bypasses receiver-overridden methods (so `bind(liar).call`
## returns the real `#class` even if `liar` defines its own).
## We route through normal do_call — the override wins. Tilt's
## scope objects don't override `#class`, so the practical impact
## is metaprogramming-only; would need a "skip user methods"
## flag on Kernel-derived BoundMethods to fix.
class Kernel
end
## Encoding — minimal stub for codebases that use the encoding
## API (ERB's compiler does at lib/erb/compiler.rb:317 / :461
## to detect the source encoding from a magic comment). rubyrs
## stores raw bytes with no per-string encoding tag, so every
## String reports as UTF-8 and every encoding is treated as
## ASCII-compatible / non-dummy. `Encoding.find(name)` returns
## the predefined constant for the standard names (singleton
## identity stable across calls) and raises ArgumentError for
## unknown names. Identity guarantee: `s.encoding ==
## Encoding.find("UTF-8")` works because the find returns the
## same `Encoding::UTF_8` instance the dispatch.rs intercept
## reads.
##
## Predefined constants cover the names ERB / cgi/util / similar
## stdlib-shaped consumers reach for; add more as real targets
## need them. `Encoding::BINARY` is the canonical CRuby alias
## for `ASCII_8BIT`.
class Encoding
  ## `Encoding.find(name)` returns the singleton instance for each
  ## of the four predefined encoding names. Identity is stable for
  ## the standard names — `Encoding.find("UTF-8").equal?(Encoding::UTF_8)`
  ## — because we return the same constant on every call. There is
  ## NO Hash cache; a case-over-name dispatch hits the four named
  ## constants directly.
  ##
  ## Why no Hash cache: `Runtime::with_config` applies `Config`
  ## (including `max_value_bytes`) BEFORE `load_preamble` runs, so
  ## any Hash mutation inside the preamble would count against tiny
  ## caps used in resource-limit tests and fail preamble load
  ## entirely.
  ##
  ## Unknown names raise `ArgumentError`, matching CRuby's
  ## `Encoding.find("missing")` shape (and avoiding the equality-
  ## breaking trap of returning two different `.new` instances for
  ## the same name).
  def self.find(name)
    # Case-insensitive only — match CRuby's actual behaviour.
    # ERB and similar consumers feed values from magic-comment
    # regex captures ("utf-8", "UTF-8", ...); without
    # normalization, lowercase magic comments would surprise
    # users with ArgumentError. CRuby does NOT fold '_' → '-'
    # (it rejects "UTF_8") and does NOT accept "UTF8" (the
    # un-hyphenated form), but does fold "ASCII" → US-ASCII
    # and "BINARY" → ASCII-8BIT — verified empirically vs
    # CRuby 3.4.
    case name.to_s.upcase
    when "UTF-8" then UTF_8
    when "US-ASCII", "ASCII" then US_ASCII
    when "ASCII-8BIT", "BINARY" then ASCII_8BIT
    else raise ArgumentError, "unknown encoding name - " + name.to_s
    end
  end

  def initialize(name)
    @name = name
  end

  def name
    @name
  end

  def to_s
    @name
  end

  def inspect
    # Built with concat — using the quote-then-hash sequence
    # inline would close the outer raw-string delimiter at
    # Rust parse time.
    '#<Encoding:' + @name + '>'
  end

  ## Always false in our subset — we don't model dummy encodings
  ## (the ones CRuby uses for, e.g., UTF-16 where you must know
  ## the byte order). Real codebases gate ASCII-safety checks on
  ## this; returning false keeps the happy path.
  def dummy?
    false
  end

  ## Always true — UTF-8, US-ASCII, and ASCII-8BIT (the only
  ## names we serve up) are all ASCII-compatible.
  def ascii_compatible?
    true
  end
end
Encoding::UTF_8 = Encoding.new("UTF-8")
Encoding::US_ASCII = Encoding.new("US-ASCII")
Encoding::ASCII_8BIT = Encoding.new("ASCII-8BIT")
Encoding::BINARY = Encoding::ASCII_8BIT

## Version sentinels. Real codebases use `RUBY_VERSION >= '3'`
## (tilt does at template.rb:239) to pick between bind_call and
## bind.call paths. We claim a recent CRuby version to opt into
## the modern branches. RUBY_PLATFORM identifies the host
## interpreter — "rubyrs" makes it obvious in any platform-
## conditional code that this isn't CRuby. RUBY_ENGINE follows
## CRuby's convention — "ruby" for MRI; engine-specific gems
## (msgpack's Factory::Pool, sidekiq, etc.) gate behaviour on
## `RUBY_ENGINE == "ruby"`, and reporting the canonical value
## opts into those branches. The truthful "rubyrs" engine tag
## lives in RUBY_PLATFORM for the rare consumer that wants to
## detect us specifically.
RUBY_VERSION = "3.4.0".freeze
RUBY_PLATFORM = "rubyrs".freeze
RUBY_ENGINE = "ruby".freeze
## `class MatchData; ... end` is loaded from
## `preamble/match_data.rb` BEFORE this `PREAMBLE` eval — the
## Rust-side `Vm::materialize_match_data` needs the class to
## exist before any `String#match` hit lands.
## `class Comparable; ... end` is loaded from
## `preamble/comparable.rb` BEFORE this `PREAMBLE` eval. The
## comment that used to describe Comparable here (about
## `include Comparable` semantics and the ArgumentError-on-nil
## rule) moved to the externalised file's header.
## `class Enumerable; end` (empty stub so `include Enumerable`
## doesn't crash) is loaded from `preamble/enumerable.rb` AFTER
## this `PREAMBLE` eval; the full rationale lives in the
## externalised file's header.
"#;
        self.eval(PREAMBLE, "<rubyrs:preamble>")
            .expect("ICE: failed to load built-in exception preamble");
        // Enumerable — empty stub so `class Foo; include
        // Enumerable; def each; ...; end; end` doesn't crash.
        // Loaded after the main PREAMBLE because nothing in the
        // remaining inline fragments references the Enumerable
        // constant; user code reaching for `include Enumerable`
        // resolves it on demand.
        self.eval(
            include_str!("preamble/enumerable.rb"),
            "<rubyrs:preamble:enumerable>",
        )
            .expect("ICE: failed to load Enumerable preamble");
        // Tier 1 seeded `Random` class. Lives in its own file so
        // the preamble stays focused on exception-hierarchy +
        // class-shell shapes; PRNG logic is meaty enough that
        // inlining it as a const string buries the algorithm.
        // ADR 0017 row 131 puts the seeded mode in Tier 1, so
        // this loads unconditionally — not gated behind
        // `--features stdlib`.
        self.eval(
            include_str!("preamble/random.rb"),
            "<rubyrs:preamble:random>",
        )
            .expect("ICE: failed to load Random preamble");
        // Tier 1 SecureRandom shim — wraps the Random class
        // above. Same Tier 1 placement rationale as Random;
        // the cryptographic guarantee is traded for determinism
        // (ADR 0017 row 131). Loaded after Random so the
        // module's `Random.new(0)` default initialisation can
        // resolve the constant.
        self.eval(
            include_str!("preamble/securerandom.rb"),
            "<rubyrs:preamble:securerandom>",
        )
            .expect("ICE: failed to load SecureRandom preamble");
        // Tier 1 `Time` class — capability-injected via
        // `Config::time_now` / the `__time_now_raw` Kernel
        // primitive. Pure Ruby per the Path A decision documented
        // in `perf/time_microbench_results.md`. Loaded
        // unconditionally; default no-injection makes `Time.now`
        // raise (ADR 0017 Rule 1 deterministic-default).
        self.eval(
            include_str!("preamble/time.rb"),
            "<rubyrs:preamble:time>",
        )
            .expect("ICE: failed to load Time preamble");
    }

    /// Replace the runtime's stdout sink.
    ///
    /// **Per ADR 0017 the default sink is `std::io::sink()`**, not
    /// process stdout — `Runtime::new()` is silent until the host
    /// calls this method to wire up where script output should go.
    /// The CLI binary `rubyrs` (in `crates/rubyrs/src/main.rs`) wires
    /// it to `std::io::stdout()`, which is why `rubyrs script.rb`
    /// behaves like CRuby; library embedders choose their own sink
    /// (`Vec<u8>` buffer, `tempfile::NamedTempFile`, a process pipe,
    /// `std::io::sink()` itself when output should be discarded).
    pub fn set_stdout(&mut self, w: Box<dyn Write>) {
        self.vm.stdout = w;
    }

    /// Snapshot of the per-call-site inline-cache hit / miss
    /// counters accumulated since this `Runtime` was constructed.
    /// Returns a meaningful `IcStats` only when rubyrs was built
    /// with the `ic-stats` cargo feature; without it, `IcStats` is
    /// a zero-sized type and reads as `Default`.
    pub fn ic_stats(&self) -> IcStats {
        self.vm.ic_stats.clone()
    }

    /// Register a host function callable from Ruby code with `name(args)`.
    /// The function receives evaluated argument values and returns either
    /// a `Value` or a `Trap`.
    ///
    /// Calling `register_fn` (or [`Runtime::register_fn_v2`]) with the
    /// same name replaces any previous registration — v1 and v2 share
    /// a single slot per name. Class- or instance-attached methods
    /// installed by a C extension live in independent dispatch tables
    /// and are NOT affected by this call.
    pub fn register_fn<F>(&mut self, name: &str, f: F)
    where
        F: Fn(&[Value]) -> Result<Value, Trap> + 'static,
    {
        let id = self.vm.interner.intern(name);
        self.vm.host_fns.insert(id, vm::HostFnSlot::V1(Rc::new(f)));
    }

    /// Variant of [`Runtime::register_fn`] whose closure also receives a
    /// [`HostCtx`] handle for reading heap-y arguments.
    ///
    /// Use this when the Ruby caller passes an `Array` or `Hash` shape
    /// that the closure needs to inspect — `Value::Array` and
    /// `Value::Hash` are opaque heap handles, so the v1 `&[Value]`-only
    /// signature can't reach their contents from inside the closure.
    /// `HostCtx::resolve_array` / `resolve_hash` borrow directly from
    /// the heap, no clone.
    ///
    /// The ctx is read-only by design (see the [`HostCtx`] doc for the
    /// soundness argument). Re-entrant eval needs the cext path, not
    /// this one.
    ///
    /// Replaces any previous v1 or v2 registration under the same name
    /// (same slot as [`Runtime::register_fn`]). Class- or instance-
    /// attached methods installed by a C extension live in independent
    /// dispatch tables and are NOT affected by this call.
    pub fn register_fn_v2<F>(&mut self, name: &str, f: F)
    where
        F: Fn(&HostCtx, &[Value]) -> Result<Value, Trap> + 'static,
    {
        let id = self.vm.interner.intern(name);
        self.vm.host_fns.insert(id, vm::HostFnSlot::V2(Rc::new(f)));
    }

    /// Parse, compile, and run a Ruby source. The returned value is the
    /// final expression of the script; embedders can ignore it for
    /// statements with no return value.
    pub fn eval(&mut self, source: &str, filename: &str) -> Result<Value, Trap> {
        let filename_rc: Rc<str> = Rc::from(filename);
        let source_rc: Rc<str> = Rc::from(source);
        // Single source-of-truth map on the Vm. Backtrace
        // formatting (`Runtime::line_for`) and dispatch-time
        // helpers (`Method#source_location`) both consult it.
        // Kernel builtins that compile new Ruby at runtime —
        // currently `require_relative` — insert here too,
        // so traps and source_location stay accurate for code
        // loaded outside the top-level `eval` path.
        self.vm.sources.insert(filename_rc.clone(), source_rc);

        let parse_result = ruby_prism::parse(source.as_bytes());
        let mut errors_iter = parse_result.errors().peekable();
        if errors_iter.peek().is_some() {
            let msg = error::format_prism_errors(source, errors_iter);
            return Err(Trap {
                err: RubyError::SyntaxError { msg },
                backtrace: vec![],
            });
        }
        let (prog, ast_errors) = ast::tr_with_errors_on_source(
            &parse_result.node(),
            parse_result.source(),
        );
        if !ast_errors.is_empty() {
            // AST translation hit one or more Prism nodes the
            // language subset doesn't cover. Surface as a
            // SyntaxError so embedders see a Trap they can format
            // and report, rather than a host-side panic.
            return Err(Trap {
                err: RubyError::SyntaxError { msg: ast_errors.join("; ") },
                backtrace: vec![],
            });
        }
        let entry = compiler::compile_proto(
            "<main>".into(), vec![], &[prog], filename_rc,
            &mut self.vm.protos, &mut self.vm.interner, &mut self.vm.cache_counter,
        );
        let cache_count = self.vm.cache_counter as usize;
        self.vm.ensure_call_caches(cache_count);
        // A previous `eval` on this Runtime may have left frames,
        // operand-stack residue, or pins behind if it ended in a
        // Trap (uncaught exception, fuel exhaustion, deadline hit).
        // Class definitions and the heap legitimately persist
        // across calls — that's part of the embedding contract.
        // The dispatch state shouldn't. Clear it now so the new
        // eval starts from a known baseline.
        self.vm.frames.clear();
        self.vm.stack.clear();
        self.vm.pinned.clear();
        self.vm.break_signaled = false;
        self.vm.method_return = None;
        self.vm.pending_loop_transfer = None;
        // Anchor the wall-clock deadline (P2-14a) to *this* eval
        // call. Each `eval` re-computes the absolute Instant from
        // the runtime's stored Duration, so a host can reuse a
        // Runtime across many short evaluations without inheriting
        // a stale timer. `None` (unlimited) is the default.
        if let Some(d) = self.deadline {
            self.vm.deadline_at = Some(std::time::Instant::now() + d);
            self.vm.op_counter = 0;
        }
        // PinGuard balance check: pinned was just zeroed; after
        // run, it must still be zero. The assert is debug-only —
        // release builds skip so a regression won't crash a host.
        let pinned_before = self.vm.pinned.len();
        let result = self.vm.run(entry);
        // Clear the deadline after eval so subsequent calls don't
        // inherit a (now-stale) Instant.
        self.vm.deadline_at = None;
        debug_assert_eq!(
            self.vm.pinned.len(), pinned_before,
            "PinGuard imbalance: pinned was {}, now {} after eval",
            pinned_before, self.vm.pinned.len(),
        );
        result
    }

    /// Number of distinct symbols currently interned by this
    /// runtime. Hosts can use this to size `Config::max_symbols`
    /// relative to the baseline established by the preamble + any
    /// prior `eval` calls.
    pub fn symbol_count(&self) -> usize {
        self.vm.interner.len()
    }

    pub fn eval_file(&mut self, path: &Path) -> Result<Value, Trap> {
        let source = std::fs::read_to_string(path).map_err(|e| Trap {
            err: RubyError::SyntaxError {
                msg: format!("cannot read {}: {}", path.display(), e),
            },
            backtrace: vec![],
        })?;
        let filename = path.to_string_lossy().into_owned();
        self.eval(&source, &filename)
    }

    /// Format a [`Trap`] CRuby-style:
    /// `file:line:in 'method': msg (Class)`, with one `\tfrom ...` line
    /// per remaining backtrace frame.
    ///
    /// Uses the source texts retained from prior `eval` calls to resolve
    /// byte offsets into line numbers.
    pub fn format_trap(&self, trap: &Trap) -> String {
        use std::fmt::Write as _;
        let mut out = String::new();
        let frames = &trap.backtrace;
        // For an uncaught Ruby exception we surface the script's
        // exception class name (e.g. `MyError`), not the host-side
        // "Uncaught" tag. Matches CRuby's
        // `foo.rb:1: msg (MyError)` style.
        let cls: String = match &trap.err {
            RubyError::Uncaught { class_name, .. } => class_name.clone(),
            other => other.class_name().to_string(),
        };
        let msg = trap.err.message();
        if let Some(top) = frames.first() {
            let line = self.line_for(&top.filename, top.span.byte_offset);
            let _ = writeln!(out, "{}:{}:in `{}': {} ({})", top.filename, line, top.method, msg, cls);
            for f in frames.iter().skip(1) {
                let line = self.line_for(&f.filename, f.span.byte_offset);
                let _ = writeln!(out, "\tfrom {}:{}:in `{}'", f.filename, line, f.method);
            }
        } else {
            let _ = writeln!(out, "rubyrs: {} ({})", msg, cls);
        }
        out
    }

    fn line_for(&self, filename: &str, byte_offset: u32) -> u32 {
        match self.vm.sources.get(filename) {
            Some(src) => error::line_col(src, byte_offset).0,
            None => 0,
        }
    }

    /// Resolve a `SymId` back to its string representation.
    pub fn resolve_sym(&self, sym: SymId) -> &str {
        self.vm.interner.resolve(sym)
    }

    /// Unpack a `Value::Array` into a Rust `Vec<Value>` by cloning elements.
    /// Returns `None` if the value is not an Array.
    pub fn resolve_array(&self, val: &Value) -> Option<Vec<Value>> {
        if let Value::Array(id) = val {
            Some(self.vm.heap.array(*id).clone())
        } else {
            None
        }
    }

    /// Unpack a `Value::Hash` into a Rust `Vec<(Value, Value)>` by cloning.
    /// Returns `None` if the value is not a Hash.
    pub fn resolve_hash(&self, val: &Value) -> Option<Vec<(Value, Value)>> {
        if let Value::Hash(id) = val {
            Some(self.vm.heap.hash(*id).clone())
        } else {
            None
        }
    }
}

impl Default for Runtime {
    fn default() -> Self { Self::new() }
}

impl Drop for Runtime {
    /// PR #60 review #14: defense-in-depth reset of the per-thread
    /// cext STATE on Vm teardown. Pairs with the reset in
    /// `with_config` — together they ensure any cext call that
    /// happens between `drop(this_rt)` and `new(next_rt)` sees a
    /// clean STATE rather than this Vm's stale handles (calling
    /// cext fns without an active Runtime is a host-side bug
    /// anyway, but this keeps the failure mode predictable).
    fn drop(&mut self) {
        #[cfg(all(feature = "cext", not(target_os = "wasi")))]
        rubyrs_cext::reset_state();
    }
}

#[cfg(test)]
mod caps_guard_tests {
    use super::*;
    use std::panic::{catch_unwind, AssertUnwindSafe};
    use std::time::Duration;

    /// `CapsGuard`'s whole purpose is to be panic-safe — Drop
    /// must fire on unwinding and restore caps even when the
    /// guarded scope panics. Without this, an embedder that
    /// catches the unwind via `catch_unwind` (rubund evaluating
    /// many gemspecs in batch, fuzz harnesses, ...) salvages a
    /// Runtime with all sandbox caps silently zeroed.
    ///
    /// Test directly against the private guard rather than
    /// through `Runtime::with_config`, because the production
    /// path is engineered so `load_preamble` doesn't panic — we
    /// need to simulate the panic to prove the guarantee holds
    /// if it ever did.
    #[test]
    fn caps_guard_restores_on_panic_in_guarded_scope() {
        let mut rt = Runtime::new();
        // Stamp recognisable cap values so the assertion can
        // distinguish "restored" from "default".
        rt.vm.fuel = Some(123);
        rt.vm.max_frames = Some(45);
        rt.vm.max_symbols = Some(678);
        rt.vm.max_value_bytes = Some(9012);
        rt.vm.heap.max_live = Some(34);
        rt.deadline = Some(Duration::from_millis(56));
        rt.vm.stress_gc = true;

        // Simulate the preamble panicking inside the guarded scope.
        // `AssertUnwindSafe` because Runtime isn't UnwindSafe; the
        // test is the one asserting it's safe to unwind through.
        let result = catch_unwind(AssertUnwindSafe(|| {
            let _guard = CapsGuard::lift(&mut rt);
            // Inside the guard, caps should be zero.
            assert!(_guard.rt.vm.fuel.is_none(), "lift should clear fuel");
            assert!(_guard.rt.vm.max_frames.is_none());
            assert!(_guard.rt.vm.max_symbols.is_none());
            assert!(_guard.rt.vm.max_value_bytes.is_none());
            assert!(_guard.rt.vm.heap.max_live.is_none());
            assert!(_guard.rt.deadline.is_none());
            assert!(!_guard.rt.vm.stress_gc);
            panic!("simulated preamble panic");
        }));

        assert!(result.is_err(), "guarded scope should have panicked");
        // After unwind, every cap is back where we stamped it.
        assert_eq!(rt.vm.fuel, Some(123));
        assert_eq!(rt.vm.max_frames, Some(45));
        assert_eq!(rt.vm.max_symbols, Some(678));
        assert_eq!(rt.vm.max_value_bytes, Some(9012));
        assert_eq!(rt.vm.heap.max_live, Some(34));
        assert_eq!(rt.deadline, Some(Duration::from_millis(56)));
        assert!(rt.vm.stress_gc);
    }

    /// Non-panic happy path — equivalent to what `with_config`
    /// does on a successful preamble load. Locks in that the
    /// guard's normal-exit Drop also restores correctly (i.e.
    /// we're not relying on the panic to trigger restore).
    #[test]
    fn caps_guard_restores_on_normal_scope_exit() {
        let mut rt = Runtime::new();
        rt.vm.fuel = Some(999);
        {
            let _guard = CapsGuard::lift(&mut rt);
            assert!(_guard.rt.vm.fuel.is_none());
        }
        assert_eq!(rt.vm.fuel, Some(999));
    }
}
