//! rubyrs — a tiny Ruby-subset runtime, embeddable in Rust hosts.
//!
//! # Quick start
//!
//! ```no_run
//! use rubyrs::{Runtime, Value};
//!
//! let mut rt = Runtime::new();
//! rt.eval(r#"puts "hello, world""#, "inline").unwrap();
//!
//! // Register a host function callable from Ruby:
//! rt.register_fn("host_pid", |_args| Ok(Value::Int(std::process::id() as i64)));
//! rt.eval(r#"puts "pid is #{host_pid}""#, "inline").unwrap();
//! ```
//!
//! See [`docs/SUBSET.md`](https://github.com/linyiru/rubyrs/blob/master/docs/SUBSET.md)
//! for the Ruby semantics this runtime does and does not support.

mod ast;
mod bytecode;
mod compiler;
mod error;
mod heap;
mod intern;
mod value;
mod vm;

use std::collections::HashMap;
use std::io::Write;
use std::path::Path;
use std::rc::Rc;

pub use error::{RubyError, Span, Trap, TrapFrame};
pub use value::Value;
pub use intern::SymId;

// C-ext compat (spike Level 0): the `rb_*` functions from `rubyrs-cext`
// are only ever called from dlopen'd C extensions — there is no Rust
// call site for the linker to see. Without this `#[used]` static
// holding raw function pointers, dead-code elimination drops them from
// the rubyrs binary and `dlsym` from the bundle returns NULL.
//
// `Qnil` / `Qtrue` / `Qfalse` get their own `#[used]` on the statics
// themselves over in `rubyrs-cext`; functions need this indirection
// because `#[used]` only applies to statics, not function definitions.
// Function pointers are `Sync`; using strongly-typed statics avoids
// the `fn as usize` cast which isn't allowed in const context.
#[used]
static _RB_STR_NEW_CSTR: unsafe extern "C" fn(*const std::ffi::c_char) -> rubyrs_cext::Value =
    rubyrs_cext::rb_str_new_cstr;
#[used]
static _RB_STR_NEW: unsafe extern "C" fn(*const std::ffi::c_char, std::ffi::c_long) -> rubyrs_cext::Value =
    rubyrs_cext::rb_str_new;
#[used]
static _RSTRING_PTR: unsafe extern "C" fn(rubyrs_cext::Value) -> *const std::ffi::c_char =
    rubyrs_cext::RSTRING_PTR;
#[used]
static _RSTRING_LEN: unsafe extern "C" fn(rubyrs_cext::Value) -> std::ffi::c_long =
    rubyrs_cext::RSTRING_LEN;
#[used]
static _RB_DEFINE_GLOBAL_FUNCTION: unsafe extern "C" fn(
    *const std::ffi::c_char,
    rubyrs_cext::OpaqueFn,
    std::ffi::c_int,
) = rubyrs_cext::rb_define_global_function;
#[used]
static _RB_STR_NEW_FROZEN: unsafe extern "C" fn(rubyrs_cext::Value) -> rubyrs_cext::Value =
    rubyrs_cext::rb_str_new_frozen;
#[used]
static _RB_STRING_VALUE_CSTR: unsafe extern "C" fn(*mut rubyrs_cext::Value) -> *const std::ffi::c_char =
    rubyrs_cext::rb_string_value_cstr;
#[used]
static _RB_STRING_VALUE_PTR: unsafe extern "C" fn(*mut rubyrs_cext::Value) -> *const std::ffi::c_char =
    rubyrs_cext::rb_string_value_ptr;
#[used]
static _RB_INT2NUM: unsafe extern "C" fn(std::ffi::c_int) -> rubyrs_cext::Value =
    rubyrs_cext::rb_int2num;
#[used]
static _RB_LONG2NUM: unsafe extern "C" fn(std::ffi::c_long) -> rubyrs_cext::Value =
    rubyrs_cext::rb_long2num;
#[used]
static _RB_NUM2INT: unsafe extern "C" fn(rubyrs_cext::Value) -> std::ffi::c_int =
    rubyrs_cext::rb_num2int;
#[used]
static _RB_NUM2LONG: unsafe extern "C" fn(rubyrs_cext::Value) -> std::ffi::c_long =
    rubyrs_cext::rb_num2long;
#[used]
static _RB_NUM2ULONG: unsafe extern "C" fn(rubyrs_cext::Value) -> std::ffi::c_ulong =
    rubyrs_cext::rb_num2ulong;
#[used]
static _RB_DEFINE_MODULE: unsafe extern "C" fn(*const std::ffi::c_char) -> rubyrs_cext::Value =
    rubyrs_cext::rb_define_module;
#[used]
static _RB_DEFINE_CLASS_UNDER: unsafe extern "C" fn(
    rubyrs_cext::Value,
    *const std::ffi::c_char,
    rubyrs_cext::Value,
) -> rubyrs_cext::Value = rubyrs_cext::rb_define_class_under;
#[used]
static _RB_DEFINE_SINGLETON_METHOD: unsafe extern "C" fn(
    rubyrs_cext::Value,
    *const std::ffi::c_char,
    rubyrs_cext::OpaqueFn,
    std::ffi::c_int,
) = rubyrs_cext::rb_define_singleton_method;
#[used]
static _RB_INTERN: unsafe extern "C" fn(*const std::ffi::c_char) -> rubyrs_cext::ID =
    rubyrs_cext::rb_intern;
#[used]
static _RB_FUNCALLV: unsafe extern "C" fn(
    rubyrs_cext::Value,
    rubyrs_cext::ID,
    std::ffi::c_int,
    *const rubyrs_cext::Value,
) -> rubyrs_cext::Value = rubyrs_cext::rb_funcallv;

// Public Prism node-class manifests. Generated by build.rs from
// `data/supported_prism_nodes.txt` and `data/rides_along_prism_nodes.txt`,
// and validated against `src/ast.rs` — see build.rs. Consumed by
// `rubyrs-gapscan` as the single source of truth for the supported subset.
include!(concat!(env!("OUT_DIR"), "/prism_node_sets.rs"));

/// Configuration for a [`Runtime`]. Defaults are unlimited; tighten for
/// untrusted scripts.
#[derive(Default)]
pub struct Config {
    /// When true, every potential GC point triggers a full collection.
    /// Useful for catching root-set bugs in host code; rough on
    /// performance. Equivalent to `STRESS_GC=1` env var.
    pub stress_gc: bool,
    /// If `Some(n)`, dispatching more than `n` ops returns a
    /// `ResourceExhausted` trap. Includes ops inside blocks via
    /// `dispatch_until`, so a runaway `[1].each { while true ... }`
    /// cannot bypass the limit.
    pub fuel: Option<u64>,
    /// If `Some(n)`, allocating past `n` simultaneously-live heap
    /// objects (Instance / Array / Hash) returns a `ResourceExhausted`
    /// trap. Checked after `maybe_gc`, so only steady-state allocation
    /// counts.
    pub max_heap_objects: Option<usize>,
    /// If `Some(n)`, pushing past `n` simultaneously-live frames
    /// returns a `ResourceExhausted` trap before the host's Rust stack
    /// can overflow.
    pub max_frames: Option<usize>,
    /// If `Some(n)`, runtime `String#to_sym` (and any other future
    /// script-driven intern path) traps when interning would push
    /// the total beyond `n` distinct symbols. Compile-time intern
    /// (method names, ivar names, string literals in source) is
    /// not capped — it's bounded by source size, which the host
    /// already controls by how big a script it feeds `eval`.
    /// Defends against `arr.map { |x| x.to_s.to_sym }`-style loops
    /// that fuel can't usefully bound.
    pub max_symbols: Option<usize>,
    /// If `Some(n)`, individual `String` / `Array` / `Hash` values
    /// can't grow past `n` bytes of content. String size is the
    /// byte length; Array/Hash size is `len * size_of::<Value>()`
    /// (or `* size_of::<(Value, Value)>()` for Hash). Checked at
    /// mutation sites: `String#+` / `String#*` / `Array#push` /
    /// `Array#<<` / `Array#[]=` / `Hash#[]=`. Heap-cap caps
    /// *number* of live objects (good against shallow alloc
    /// storms); this caps *individual* object size (good against
    /// `"a" * 10_000_000`, which is one heap object that grabs 10 MB).
    pub max_value_bytes: Option<usize>,
    /// If `Some(d)`, an `eval` call that runs longer than `d`
    /// wall-clock time returns a `ResourceExhausted` trap. Checked
    /// every 1024 ops (cheap and precise enough for the host-side
    /// timeouts this is meant to enforce — request budgets,
    /// gemspec-evaluation guards, similar). The deadline is
    /// per-`eval`: each call re-anchors the clock, so a host can
    /// reuse a Runtime across many short evaluations without each
    /// one inheriting the previous timer.
    pub deadline: Option<std::time::Duration>,
}

/// A self-contained rubyrs runtime. State (class definitions, top-level
/// methods, registered host functions, GC heap) persists across calls to
/// [`Runtime::eval`].
pub struct Runtime {
    vm: vm::Vm,
    /// Source text per filename, retained so that backtrace formatting can
    /// resolve byte offsets to line/column without re-reading the file.
    sources: HashMap<Rc<str>, Rc<str>>,
    /// Per-call-site inline-cache id allocator, monotonically increasing
    /// across every `eval` call so subsequent compiles don't collide with
    /// cached methods from earlier ones.
    cache_counter: u32,
    /// Per-`eval` wall-clock budget (P2-14a). Retained as a
    /// Duration; an absolute `Instant` is computed at the start of
    /// each `eval` call and stored on `Vm.deadline_at`. `None` means
    /// unlimited.
    deadline: Option<std::time::Duration>,
}

impl Runtime {
    pub fn new() -> Self {
        Self::with_config(Config::default())
    }

    pub fn with_config(cfg: Config) -> Self {
        let interner = intern::Interner::new();
        let mut vm = vm::Vm::new(vec![], interner);
        if cfg.stress_gc { vm.stress_gc = true; }
        vm.fuel = cfg.fuel;
        vm.max_frames = cfg.max_frames;
        vm.heap.max_live = cfg.max_heap_objects;
        vm.max_symbols = cfg.max_symbols;
        vm.max_value_bytes = cfg.max_value_bytes;
        let mut rt = Runtime {
            vm, sources: HashMap::new(), cache_counter: 0,
            deadline: cfg.deadline,
        };
        rt.load_preamble();
        rt
    }

    /// Bootstrap the built-in Ruby class hierarchy (currently just
    /// exceptions) by `eval`-ing a small Ruby preamble. Done with the
    /// runtime's own machinery so the resulting classes look identical
    /// to user-defined ones (no special-cased C structs).
    fn load_preamble(&mut self) {
        const PREAMBLE: &str = r#"
class Exception
  def initialize(msg)
    @message = msg
  end
  def message
    @message
  end
  def to_s
    @message
  end
end
class StandardError < Exception
end
class RuntimeError < StandardError
end
class NoMethodError < StandardError
end
class ArgumentError < StandardError
end
class TypeError < StandardError
end
class NameError < StandardError
end
class IndexError < StandardError
end
class KeyError < IndexError
end
class ZeroDivisionError < StandardError
end
## Intentionally `< Exception`, NOT `< StandardError`. A bare
## `rescue => e` clause filters on `StandardError` by default,
## so attaching `ResourceExhausted` outside that subtree means
## user scripts cannot accidentally — or deliberately — swallow
## their own fuel / heap / frame trap and keep burning quota.
## CRuby uses the same pattern for `SystemExit` and `Interrupt`.
## See docs/adr/0008-resource-caps-for-untrusted-scripts.md.
class ResourceExhausted < Exception
end
## Stub classes for built-in types. Without these, `5.class` and
## friends have nothing to return; the bodies stay empty because
## built-in method dispatch goes through `primitive_call` /
## `collection_call` before any class-table lookup. Re-opening
## these from user code does work (`class Integer; def foo; end`)
## but adding methods that way won't shadow the primitive arms —
## see docs/SUBSET.md.
class Integer
end
class Float
end
class String
end
class Symbol
end
class Array
end
class Hash
end
class Range
end
class TrueClass
end
class FalseClass
end
class NilClass
end
class Proc
end
class Class
end
"#;
        self.eval(PREAMBLE, "<rubyrs:preamble>")
            .expect("ICE: failed to load built-in exception preamble");
    }

    /// Replace the runtime's stdout sink. Lets a host capture `puts` /
    /// `print` output (e.g. into a `Vec<u8>` buffer) instead of having
    /// it go to the process stdout.
    pub fn set_stdout(&mut self, w: Box<dyn Write>) {
        self.vm.stdout = w;
    }

    /// Register a host function callable from Ruby code with `name(args)`.
    /// The function receives evaluated argument values and returns either
    /// a `Value` or a `Trap`. Calling `register_fn` with the same name
    /// replaces a previous registration.
    pub fn register_fn<F>(&mut self, name: &str, f: F)
    where
        F: Fn(&[Value]) -> Result<Value, Trap> + 'static,
    {
        let id = self.vm.interner.intern(name);
        self.vm.host_fns.insert(id, Rc::new(f));
    }

    /// Parse, compile, and run a Ruby source. The returned value is the
    /// final expression of the script; embedders can ignore it for
    /// statements with no return value.
    pub fn eval(&mut self, source: &str, filename: &str) -> Result<Value, Trap> {
        let filename_rc: Rc<str> = Rc::from(filename);
        self.sources.insert(filename_rc.clone(), Rc::from(source));

        let parse_result = ruby_prism::parse(source.as_bytes());
        let errors: Vec<_> = parse_result.errors().collect();
        if !errors.is_empty() {
            let msg = errors.iter()
                .map(|e| format!("{:?}", e))
                .collect::<Vec<_>>().join("; ");
            return Err(Trap {
                err: RubyError::SyntaxError { msg },
                backtrace: vec![],
            });
        }
        let (prog, ast_errors) = ast::tr_with_errors(&parse_result.node());
        if !ast_errors.is_empty() {
            // AST translation hit one or more Prism nodes the
            // language subset doesn't cover. Surface as a
            // SyntaxError so embedders see a Trap they can format
            // and report, rather than a host-side panic.
            return Err(Trap {
                err: RubyError::SyntaxError { msg: ast_errors.join("; ") },
                backtrace: vec![],
            });
        }
        let entry = compiler::compile_proto(
            "<main>".into(), vec![], vec![], &[prog], filename_rc,
            &mut self.vm.protos, &mut self.vm.interner, &mut self.cache_counter,
        );
        self.vm.ensure_call_caches(self.cache_counter as usize);
        // A previous `eval` on this Runtime may have left frames,
        // operand-stack residue, or pins behind if it ended in a
        // Trap (uncaught exception, fuel exhaustion, deadline hit).
        // Class definitions and the heap legitimately persist
        // across calls — that's part of the embedding contract.
        // The dispatch state shouldn't. Clear it now so the new
        // eval starts from a known baseline.
        self.vm.frames.clear();
        self.vm.stack.clear();
        self.vm.pinned.clear();
        self.vm.break_signaled = false;
        // Anchor the wall-clock deadline (P2-14a) to *this* eval
        // call. Each `eval` re-computes the absolute Instant from
        // the runtime's stored Duration, so a host can reuse a
        // Runtime across many short evaluations without inheriting
        // a stale timer. `None` (unlimited) is the default.
        if let Some(d) = self.deadline {
            self.vm.deadline_at = Some(std::time::Instant::now() + d);
            self.vm.op_counter = 0;
        }
        // PinGuard balance check: pinned was just zeroed; after
        // run, it must still be zero. The assert is debug-only —
        // release builds skip so a regression won't crash a host.
        let pinned_before = self.vm.pinned.len();
        let result = self.vm.run(entry);
        // Clear the deadline after eval so subsequent calls don't
        // inherit a (now-stale) Instant.
        self.vm.deadline_at = None;
        debug_assert_eq!(
            self.vm.pinned.len(), pinned_before,
            "PinGuard imbalance: pinned was {}, now {} after eval",
            pinned_before, self.vm.pinned.len(),
        );
        result
    }

    /// Number of distinct symbols currently interned by this
    /// runtime. Hosts can use this to size `Config::max_symbols`
    /// relative to the baseline established by the preamble + any
    /// prior `eval` calls.
    pub fn symbol_count(&self) -> usize {
        self.vm.interner.len()
    }

    pub fn eval_file(&mut self, path: &Path) -> Result<Value, Trap> {
        let source = std::fs::read_to_string(path).map_err(|e| Trap {
            err: RubyError::SyntaxError {
                msg: format!("cannot read {}: {}", path.display(), e),
            },
            backtrace: vec![],
        })?;
        let filename = path.to_string_lossy().into_owned();
        self.eval(&source, &filename)
    }

    /// Format a [`Trap`] CRuby-style:
    /// `file:line:in 'method': msg (Class)`, with one `\tfrom ...` line
    /// per remaining backtrace frame.
    ///
    /// Uses the source texts retained from prior `eval` calls to resolve
    /// byte offsets into line numbers.
    pub fn format_trap(&self, trap: &Trap) -> String {
        use std::fmt::Write as _;
        let mut out = String::new();
        let frames = &trap.backtrace;
        // For an uncaught Ruby exception we surface the script's
        // exception class name (e.g. `MyError`), not the host-side
        // "Uncaught" tag. Matches CRuby's
        // `foo.rb:1: msg (MyError)` style.
        let cls: String = match &trap.err {
            RubyError::Uncaught { class_name, .. } => class_name.clone(),
            other => other.class_name().to_string(),
        };
        let msg = trap.err.message();
        if let Some(top) = frames.first() {
            let line = self.line_for(&top.filename, top.span.byte_offset);
            let _ = writeln!(out, "{}:{}:in `{}': {} ({})", top.filename, line, top.method, msg, cls);
            for f in frames.iter().skip(1) {
                let line = self.line_for(&f.filename, f.span.byte_offset);
                let _ = writeln!(out, "\tfrom {}:{}:in `{}'", f.filename, line, f.method);
            }
        } else {
            let _ = writeln!(out, "rubyrs: {} ({})", msg, cls);
        }
        out
    }

    fn line_for(&self, filename: &str, byte_offset: u32) -> u32 {
        match self.sources.get(filename) {
            Some(src) => error::line_col(src, byte_offset).0,
            None => 0,
        }
    }

    /// Resolve a `SymId` back to its string representation.
    pub fn resolve_sym(&self, sym: SymId) -> &str {
        self.vm.interner.resolve(sym)
    }

    /// Unpack a `Value::Array` into a Rust `Vec<Value>` by cloning elements.
    /// Returns `None` if the value is not an Array.
    pub fn resolve_array(&self, val: &Value) -> Option<Vec<Value>> {
        if let Value::Array(id) = val {
            Some(self.vm.heap.array(*id).clone())
        } else {
            None
        }
    }

    /// Unpack a `Value::Hash` into a Rust `Vec<(Value, Value)>` by cloning.
    /// Returns `None` if the value is not a Hash.
    pub fn resolve_hash(&self, val: &Value) -> Option<Vec<(Value, Value)>> {
        if let Value::Hash(id) = val {
            Some(self.vm.heap.hash(*id).clone())
        } else {
            None
        }
    }
}

impl Default for Runtime {
    fn default() -> Self { Self::new() }
}
