//! GENERATED by scripts/gen_prism_node_specs.rb from the prism gem's own
//! generated serialize.rb + node.rb (prism 1.9.0). Do not edit by
//! hand — re-run the script when the linked prism version changes.
//!
//! One `NodeSpec` per wire node-type id: the Ruby class the interpreted
//! deserializer would instantiate, and the (wire field kind, ivar name)
//! pairs its positional constructor args land in, in wire order.

use super::prism_materialize::FieldKind::{self, *};

/// Wire-format version this table was generated against. The materializer
/// verifies the blob header matches before trusting the table.
pub(crate) const WIRE_VERSION: (u8, u8, u8) = (1, 9, 0);

pub(crate) struct NodeSpec {
    /// Unqualified class name under `Prism::`.
    pub(crate) name: &'static str,
    /// `true` when the wire carries a leading uint32 the Ruby loader
    /// discards (DefNode's serialized-locals length).
    pub(crate) skip_uint32: bool,
    /// `(wire kind, ivar name)` in wire order, excluding the common
    /// `@source`/`@node_id`/`@location`/`@flags` prefix.
    pub(crate) fields: &'static [(FieldKind, &'static str)],
}

/// Indexed by `wire_type - 1` (wire node types are 1-based).
pub(crate) static NODE_SPECS: [NodeSpec; 151] = [
    // 1
    NodeSpec { name: "AliasGlobalVariableNode", skip_uint32: false, fields: &[(Node, "@new_name"), (Node, "@old_name"), (Location, "@keyword_loc")] },
    // 2
    NodeSpec { name: "AliasMethodNode", skip_uint32: false, fields: &[(Node, "@new_name"), (Node, "@old_name"), (Location, "@keyword_loc")] },
    // 3
    NodeSpec { name: "AlternationPatternNode", skip_uint32: false, fields: &[(Node, "@left"), (Node, "@right"), (Location, "@operator_loc")] },
    // 4
    NodeSpec { name: "AndNode", skip_uint32: false, fields: &[(Node, "@left"), (Node, "@right"), (Location, "@operator_loc")] },
    // 5
    NodeSpec { name: "ArgumentsNode", skip_uint32: false, fields: &[(NodeList, "@arguments")] },
    // 6
    NodeSpec { name: "ArrayNode", skip_uint32: false, fields: &[(NodeList, "@elements"), (OptLocation, "@opening_loc"), (OptLocation, "@closing_loc")] },
    // 7
    NodeSpec { name: "ArrayPatternNode", skip_uint32: false, fields: &[(OptNode, "@constant"), (NodeList, "@requireds"), (OptNode, "@rest"), (NodeList, "@posts"), (OptLocation, "@opening_loc"), (OptLocation, "@closing_loc")] },
    // 8
    NodeSpec { name: "AssocNode", skip_uint32: false, fields: &[(Node, "@key"), (Node, "@value"), (OptLocation, "@operator_loc")] },
    // 9
    NodeSpec { name: "AssocSplatNode", skip_uint32: false, fields: &[(OptNode, "@value"), (Location, "@operator_loc")] },
    // 10
    NodeSpec { name: "BackReferenceReadNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 11
    NodeSpec { name: "BeginNode", skip_uint32: false, fields: &[(OptLocation, "@begin_keyword_loc"), (OptNode, "@statements"), (OptNode, "@rescue_clause"), (OptNode, "@else_clause"), (OptNode, "@ensure_clause"), (OptLocation, "@end_keyword_loc")] },
    // 12
    NodeSpec { name: "BlockArgumentNode", skip_uint32: false, fields: &[(OptNode, "@expression"), (Location, "@operator_loc")] },
    // 13
    NodeSpec { name: "BlockLocalVariableNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 14
    NodeSpec { name: "BlockNode", skip_uint32: false, fields: &[(ConstantList, "@locals"), (OptNode, "@parameters"), (OptNode, "@body"), (Location, "@opening_loc"), (Location, "@closing_loc")] },
    // 15
    NodeSpec { name: "BlockParameterNode", skip_uint32: false, fields: &[(OptConstant, "@name"), (OptLocation, "@name_loc"), (Location, "@operator_loc")] },
    // 16
    NodeSpec { name: "BlockParametersNode", skip_uint32: false, fields: &[(OptNode, "@parameters"), (NodeList, "@locals"), (OptLocation, "@opening_loc"), (OptLocation, "@closing_loc")] },
    // 17
    NodeSpec { name: "BreakNode", skip_uint32: false, fields: &[(OptNode, "@arguments"), (Location, "@keyword_loc")] },
    // 18
    NodeSpec { name: "CallAndWriteNode", skip_uint32: false, fields: &[(OptNode, "@receiver"), (OptLocation, "@call_operator_loc"), (OptLocation, "@message_loc"), (Constant, "@read_name"), (Constant, "@write_name"), (Location, "@operator_loc"), (Node, "@value")] },
    // 19
    NodeSpec { name: "CallNode", skip_uint32: false, fields: &[(OptNode, "@receiver"), (OptLocation, "@call_operator_loc"), (Constant, "@name"), (OptLocation, "@message_loc"), (OptLocation, "@opening_loc"), (OptNode, "@arguments"), (OptLocation, "@closing_loc"), (OptLocation, "@equal_loc"), (OptNode, "@block")] },
    // 20
    NodeSpec { name: "CallOperatorWriteNode", skip_uint32: false, fields: &[(OptNode, "@receiver"), (OptLocation, "@call_operator_loc"), (OptLocation, "@message_loc"), (Constant, "@read_name"), (Constant, "@write_name"), (Constant, "@binary_operator"), (Location, "@binary_operator_loc"), (Node, "@value")] },
    // 21
    NodeSpec { name: "CallOrWriteNode", skip_uint32: false, fields: &[(OptNode, "@receiver"), (OptLocation, "@call_operator_loc"), (OptLocation, "@message_loc"), (Constant, "@read_name"), (Constant, "@write_name"), (Location, "@operator_loc"), (Node, "@value")] },
    // 22
    NodeSpec { name: "CallTargetNode", skip_uint32: false, fields: &[(Node, "@receiver"), (Location, "@call_operator_loc"), (Constant, "@name"), (Location, "@message_loc")] },
    // 23
    NodeSpec { name: "CapturePatternNode", skip_uint32: false, fields: &[(Node, "@value"), (Node, "@target"), (Location, "@operator_loc")] },
    // 24
    NodeSpec { name: "CaseMatchNode", skip_uint32: false, fields: &[(OptNode, "@predicate"), (NodeList, "@conditions"), (OptNode, "@else_clause"), (Location, "@case_keyword_loc"), (Location, "@end_keyword_loc")] },
    // 25
    NodeSpec { name: "CaseNode", skip_uint32: false, fields: &[(OptNode, "@predicate"), (NodeList, "@conditions"), (OptNode, "@else_clause"), (Location, "@case_keyword_loc"), (Location, "@end_keyword_loc")] },
    // 26
    NodeSpec { name: "ClassNode", skip_uint32: false, fields: &[(ConstantList, "@locals"), (Location, "@class_keyword_loc"), (Node, "@constant_path"), (OptLocation, "@inheritance_operator_loc"), (OptNode, "@superclass"), (OptNode, "@body"), (Location, "@end_keyword_loc"), (Constant, "@name")] },
    // 27
    NodeSpec { name: "ClassVariableAndWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 28
    NodeSpec { name: "ClassVariableOperatorWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@binary_operator_loc"), (Node, "@value"), (Constant, "@binary_operator")] },
    // 29
    NodeSpec { name: "ClassVariableOrWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 30
    NodeSpec { name: "ClassVariableReadNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 31
    NodeSpec { name: "ClassVariableTargetNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 32
    NodeSpec { name: "ClassVariableWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Node, "@value"), (Location, "@operator_loc")] },
    // 33
    NodeSpec { name: "ConstantAndWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 34
    NodeSpec { name: "ConstantOperatorWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@binary_operator_loc"), (Node, "@value"), (Constant, "@binary_operator")] },
    // 35
    NodeSpec { name: "ConstantOrWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 36
    NodeSpec { name: "ConstantPathAndWriteNode", skip_uint32: false, fields: &[(Node, "@target"), (Location, "@operator_loc"), (Node, "@value")] },
    // 37
    NodeSpec { name: "ConstantPathNode", skip_uint32: false, fields: &[(OptNode, "@parent"), (OptConstant, "@name"), (Location, "@delimiter_loc"), (Location, "@name_loc")] },
    // 38
    NodeSpec { name: "ConstantPathOperatorWriteNode", skip_uint32: false, fields: &[(Node, "@target"), (Location, "@binary_operator_loc"), (Node, "@value"), (Constant, "@binary_operator")] },
    // 39
    NodeSpec { name: "ConstantPathOrWriteNode", skip_uint32: false, fields: &[(Node, "@target"), (Location, "@operator_loc"), (Node, "@value")] },
    // 40
    NodeSpec { name: "ConstantPathTargetNode", skip_uint32: false, fields: &[(OptNode, "@parent"), (OptConstant, "@name"), (Location, "@delimiter_loc"), (Location, "@name_loc")] },
    // 41
    NodeSpec { name: "ConstantPathWriteNode", skip_uint32: false, fields: &[(Node, "@target"), (Location, "@operator_loc"), (Node, "@value")] },
    // 42
    NodeSpec { name: "ConstantReadNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 43
    NodeSpec { name: "ConstantTargetNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 44
    NodeSpec { name: "ConstantWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Node, "@value"), (Location, "@operator_loc")] },
    // 45
    NodeSpec { name: "DefNode", skip_uint32: true, fields: &[(Constant, "@name"), (Location, "@name_loc"), (OptNode, "@receiver"), (OptNode, "@parameters"), (OptNode, "@body"), (ConstantList, "@locals"), (Location, "@def_keyword_loc"), (OptLocation, "@operator_loc"), (OptLocation, "@lparen_loc"), (OptLocation, "@rparen_loc"), (OptLocation, "@equal_loc"), (OptLocation, "@end_keyword_loc")] },
    // 46
    NodeSpec { name: "DefinedNode", skip_uint32: false, fields: &[(OptLocation, "@lparen_loc"), (Node, "@value"), (OptLocation, "@rparen_loc"), (Location, "@keyword_loc")] },
    // 47
    NodeSpec { name: "ElseNode", skip_uint32: false, fields: &[(Location, "@else_keyword_loc"), (OptNode, "@statements"), (OptLocation, "@end_keyword_loc")] },
    // 48
    NodeSpec { name: "EmbeddedStatementsNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (OptNode, "@statements"), (Location, "@closing_loc")] },
    // 49
    NodeSpec { name: "EmbeddedVariableNode", skip_uint32: false, fields: &[(Location, "@operator_loc"), (Node, "@variable")] },
    // 50
    NodeSpec { name: "EnsureNode", skip_uint32: false, fields: &[(Location, "@ensure_keyword_loc"), (OptNode, "@statements"), (Location, "@end_keyword_loc")] },
    // 51
    NodeSpec { name: "FalseNode", skip_uint32: false, fields: &[] },
    // 52
    NodeSpec { name: "FindPatternNode", skip_uint32: false, fields: &[(OptNode, "@constant"), (Node, "@left"), (NodeList, "@requireds"), (Node, "@right"), (OptLocation, "@opening_loc"), (OptLocation, "@closing_loc")] },
    // 53
    NodeSpec { name: "FlipFlopNode", skip_uint32: false, fields: &[(OptNode, "@left"), (OptNode, "@right"), (Location, "@operator_loc")] },
    // 54
    NodeSpec { name: "FloatNode", skip_uint32: false, fields: &[(Double, "@value")] },
    // 55
    NodeSpec { name: "ForNode", skip_uint32: false, fields: &[(Node, "@index"), (Node, "@collection"), (OptNode, "@statements"), (Location, "@for_keyword_loc"), (Location, "@in_keyword_loc"), (OptLocation, "@do_keyword_loc"), (Location, "@end_keyword_loc")] },
    // 56
    NodeSpec { name: "ForwardingArgumentsNode", skip_uint32: false, fields: &[] },
    // 57
    NodeSpec { name: "ForwardingParameterNode", skip_uint32: false, fields: &[] },
    // 58
    NodeSpec { name: "ForwardingSuperNode", skip_uint32: false, fields: &[(OptNode, "@block")] },
    // 59
    NodeSpec { name: "GlobalVariableAndWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 60
    NodeSpec { name: "GlobalVariableOperatorWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@binary_operator_loc"), (Node, "@value"), (Constant, "@binary_operator")] },
    // 61
    NodeSpec { name: "GlobalVariableOrWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 62
    NodeSpec { name: "GlobalVariableReadNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 63
    NodeSpec { name: "GlobalVariableTargetNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 64
    NodeSpec { name: "GlobalVariableWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Node, "@value"), (Location, "@operator_loc")] },
    // 65
    NodeSpec { name: "HashNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (NodeList, "@elements"), (Location, "@closing_loc")] },
    // 66
    NodeSpec { name: "HashPatternNode", skip_uint32: false, fields: &[(OptNode, "@constant"), (NodeList, "@elements"), (OptNode, "@rest"), (OptLocation, "@opening_loc"), (OptLocation, "@closing_loc")] },
    // 67
    NodeSpec { name: "IfNode", skip_uint32: false, fields: &[(OptLocation, "@if_keyword_loc"), (Node, "@predicate"), (OptLocation, "@then_keyword_loc"), (OptNode, "@statements"), (OptNode, "@subsequent"), (OptLocation, "@end_keyword_loc")] },
    // 68
    NodeSpec { name: "ImaginaryNode", skip_uint32: false, fields: &[(Node, "@numeric")] },
    // 69
    NodeSpec { name: "ImplicitNode", skip_uint32: false, fields: &[(Node, "@value")] },
    // 70
    NodeSpec { name: "ImplicitRestNode", skip_uint32: false, fields: &[] },
    // 71
    NodeSpec { name: "InNode", skip_uint32: false, fields: &[(Node, "@pattern"), (OptNode, "@statements"), (Location, "@in_loc"), (OptLocation, "@then_loc")] },
    // 72
    NodeSpec { name: "IndexAndWriteNode", skip_uint32: false, fields: &[(OptNode, "@receiver"), (OptLocation, "@call_operator_loc"), (Location, "@opening_loc"), (OptNode, "@arguments"), (Location, "@closing_loc"), (OptNode, "@block"), (Location, "@operator_loc"), (Node, "@value")] },
    // 73
    NodeSpec { name: "IndexOperatorWriteNode", skip_uint32: false, fields: &[(OptNode, "@receiver"), (OptLocation, "@call_operator_loc"), (Location, "@opening_loc"), (OptNode, "@arguments"), (Location, "@closing_loc"), (OptNode, "@block"), (Constant, "@binary_operator"), (Location, "@binary_operator_loc"), (Node, "@value")] },
    // 74
    NodeSpec { name: "IndexOrWriteNode", skip_uint32: false, fields: &[(OptNode, "@receiver"), (OptLocation, "@call_operator_loc"), (Location, "@opening_loc"), (OptNode, "@arguments"), (Location, "@closing_loc"), (OptNode, "@block"), (Location, "@operator_loc"), (Node, "@value")] },
    // 75
    NodeSpec { name: "IndexTargetNode", skip_uint32: false, fields: &[(Node, "@receiver"), (Location, "@opening_loc"), (OptNode, "@arguments"), (Location, "@closing_loc"), (OptNode, "@block")] },
    // 76
    NodeSpec { name: "InstanceVariableAndWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 77
    NodeSpec { name: "InstanceVariableOperatorWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@binary_operator_loc"), (Node, "@value"), (Constant, "@binary_operator")] },
    // 78
    NodeSpec { name: "InstanceVariableOrWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 79
    NodeSpec { name: "InstanceVariableReadNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 80
    NodeSpec { name: "InstanceVariableTargetNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 81
    NodeSpec { name: "InstanceVariableWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Node, "@value"), (Location, "@operator_loc")] },
    // 82
    NodeSpec { name: "IntegerNode", skip_uint32: false, fields: &[(Integer, "@value")] },
    // 83
    NodeSpec { name: "InterpolatedMatchLastLineNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (NodeList, "@parts"), (Location, "@closing_loc")] },
    // 84
    NodeSpec { name: "InterpolatedRegularExpressionNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (NodeList, "@parts"), (Location, "@closing_loc")] },
    // 85
    NodeSpec { name: "InterpolatedStringNode", skip_uint32: false, fields: &[(OptLocation, "@opening_loc"), (NodeList, "@parts"), (OptLocation, "@closing_loc")] },
    // 86
    NodeSpec { name: "InterpolatedSymbolNode", skip_uint32: false, fields: &[(OptLocation, "@opening_loc"), (NodeList, "@parts"), (OptLocation, "@closing_loc")] },
    // 87
    NodeSpec { name: "InterpolatedXStringNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (NodeList, "@parts"), (Location, "@closing_loc")] },
    // 88
    NodeSpec { name: "ItLocalVariableReadNode", skip_uint32: false, fields: &[] },
    // 89
    NodeSpec { name: "ItParametersNode", skip_uint32: false, fields: &[] },
    // 90
    NodeSpec { name: "KeywordHashNode", skip_uint32: false, fields: &[(NodeList, "@elements")] },
    // 91
    NodeSpec { name: "KeywordRestParameterNode", skip_uint32: false, fields: &[(OptConstant, "@name"), (OptLocation, "@name_loc"), (Location, "@operator_loc")] },
    // 92
    NodeSpec { name: "LambdaNode", skip_uint32: false, fields: &[(ConstantList, "@locals"), (Location, "@operator_loc"), (Location, "@opening_loc"), (Location, "@closing_loc"), (OptNode, "@parameters"), (OptNode, "@body")] },
    // 93
    NodeSpec { name: "LocalVariableAndWriteNode", skip_uint32: false, fields: &[(Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value"), (Constant, "@name"), (VarUint, "@depth")] },
    // 94
    NodeSpec { name: "LocalVariableOperatorWriteNode", skip_uint32: false, fields: &[(Location, "@name_loc"), (Location, "@binary_operator_loc"), (Node, "@value"), (Constant, "@name"), (Constant, "@binary_operator"), (VarUint, "@depth")] },
    // 95
    NodeSpec { name: "LocalVariableOrWriteNode", skip_uint32: false, fields: &[(Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value"), (Constant, "@name"), (VarUint, "@depth")] },
    // 96
    NodeSpec { name: "LocalVariableReadNode", skip_uint32: false, fields: &[(Constant, "@name"), (VarUint, "@depth")] },
    // 97
    NodeSpec { name: "LocalVariableTargetNode", skip_uint32: false, fields: &[(Constant, "@name"), (VarUint, "@depth")] },
    // 98
    NodeSpec { name: "LocalVariableWriteNode", skip_uint32: false, fields: &[(Constant, "@name"), (VarUint, "@depth"), (Location, "@name_loc"), (Node, "@value"), (Location, "@operator_loc")] },
    // 99
    NodeSpec { name: "MatchLastLineNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (Location, "@content_loc"), (Location, "@closing_loc"), (Str, "@unescaped")] },
    // 100
    NodeSpec { name: "MatchPredicateNode", skip_uint32: false, fields: &[(Node, "@value"), (Node, "@pattern"), (Location, "@operator_loc")] },
    // 101
    NodeSpec { name: "MatchRequiredNode", skip_uint32: false, fields: &[(Node, "@value"), (Node, "@pattern"), (Location, "@operator_loc")] },
    // 102
    NodeSpec { name: "MatchWriteNode", skip_uint32: false, fields: &[(Node, "@call"), (NodeList, "@targets")] },
    // 103
    NodeSpec { name: "MissingNode", skip_uint32: false, fields: &[] },
    // 104
    NodeSpec { name: "ModuleNode", skip_uint32: false, fields: &[(ConstantList, "@locals"), (Location, "@module_keyword_loc"), (Node, "@constant_path"), (OptNode, "@body"), (Location, "@end_keyword_loc"), (Constant, "@name")] },
    // 105
    NodeSpec { name: "MultiTargetNode", skip_uint32: false, fields: &[(NodeList, "@lefts"), (OptNode, "@rest"), (NodeList, "@rights"), (OptLocation, "@lparen_loc"), (OptLocation, "@rparen_loc")] },
    // 106
    NodeSpec { name: "MultiWriteNode", skip_uint32: false, fields: &[(NodeList, "@lefts"), (OptNode, "@rest"), (NodeList, "@rights"), (OptLocation, "@lparen_loc"), (OptLocation, "@rparen_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 107
    NodeSpec { name: "NextNode", skip_uint32: false, fields: &[(OptNode, "@arguments"), (Location, "@keyword_loc")] },
    // 108
    NodeSpec { name: "NilNode", skip_uint32: false, fields: &[] },
    // 109
    NodeSpec { name: "NoKeywordsParameterNode", skip_uint32: false, fields: &[(Location, "@operator_loc"), (Location, "@keyword_loc")] },
    // 110
    NodeSpec { name: "NumberedParametersNode", skip_uint32: false, fields: &[(UInt8, "@maximum")] },
    // 111
    NodeSpec { name: "NumberedReferenceReadNode", skip_uint32: false, fields: &[(VarUint, "@number")] },
    // 112
    NodeSpec { name: "OptionalKeywordParameterNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Node, "@value")] },
    // 113
    NodeSpec { name: "OptionalParameterNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc"), (Location, "@operator_loc"), (Node, "@value")] },
    // 114
    NodeSpec { name: "OrNode", skip_uint32: false, fields: &[(Node, "@left"), (Node, "@right"), (Location, "@operator_loc")] },
    // 115
    NodeSpec { name: "ParametersNode", skip_uint32: false, fields: &[(NodeList, "@requireds"), (NodeList, "@optionals"), (OptNode, "@rest"), (NodeList, "@posts"), (NodeList, "@keywords"), (OptNode, "@keyword_rest"), (OptNode, "@block")] },
    // 116
    NodeSpec { name: "ParenthesesNode", skip_uint32: false, fields: &[(OptNode, "@body"), (Location, "@opening_loc"), (Location, "@closing_loc")] },
    // 117
    NodeSpec { name: "PinnedExpressionNode", skip_uint32: false, fields: &[(Node, "@expression"), (Location, "@operator_loc"), (Location, "@lparen_loc"), (Location, "@rparen_loc")] },
    // 118
    NodeSpec { name: "PinnedVariableNode", skip_uint32: false, fields: &[(Node, "@variable"), (Location, "@operator_loc")] },
    // 119
    NodeSpec { name: "PostExecutionNode", skip_uint32: false, fields: &[(OptNode, "@statements"), (Location, "@keyword_loc"), (Location, "@opening_loc"), (Location, "@closing_loc")] },
    // 120
    NodeSpec { name: "PreExecutionNode", skip_uint32: false, fields: &[(OptNode, "@statements"), (Location, "@keyword_loc"), (Location, "@opening_loc"), (Location, "@closing_loc")] },
    // 121
    NodeSpec { name: "ProgramNode", skip_uint32: false, fields: &[(ConstantList, "@locals"), (Node, "@statements")] },
    // 122
    NodeSpec { name: "RangeNode", skip_uint32: false, fields: &[(OptNode, "@left"), (OptNode, "@right"), (Location, "@operator_loc")] },
    // 123
    NodeSpec { name: "RationalNode", skip_uint32: false, fields: &[(Integer, "@numerator"), (Integer, "@denominator")] },
    // 124
    NodeSpec { name: "RedoNode", skip_uint32: false, fields: &[] },
    // 125
    NodeSpec { name: "RegularExpressionNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (Location, "@content_loc"), (Location, "@closing_loc"), (Str, "@unescaped")] },
    // 126
    NodeSpec { name: "RequiredKeywordParameterNode", skip_uint32: false, fields: &[(Constant, "@name"), (Location, "@name_loc")] },
    // 127
    NodeSpec { name: "RequiredParameterNode", skip_uint32: false, fields: &[(Constant, "@name")] },
    // 128
    NodeSpec { name: "RescueModifierNode", skip_uint32: false, fields: &[(Node, "@expression"), (Location, "@keyword_loc"), (Node, "@rescue_expression")] },
    // 129
    NodeSpec { name: "RescueNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (NodeList, "@exceptions"), (OptLocation, "@operator_loc"), (OptNode, "@reference"), (OptLocation, "@then_keyword_loc"), (OptNode, "@statements"), (OptNode, "@subsequent")] },
    // 130
    NodeSpec { name: "RestParameterNode", skip_uint32: false, fields: &[(OptConstant, "@name"), (OptLocation, "@name_loc"), (Location, "@operator_loc")] },
    // 131
    NodeSpec { name: "RetryNode", skip_uint32: false, fields: &[] },
    // 132
    NodeSpec { name: "ReturnNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (OptNode, "@arguments")] },
    // 133
    NodeSpec { name: "SelfNode", skip_uint32: false, fields: &[] },
    // 134
    NodeSpec { name: "ShareableConstantNode", skip_uint32: false, fields: &[(Node, "@write")] },
    // 135
    NodeSpec { name: "SingletonClassNode", skip_uint32: false, fields: &[(ConstantList, "@locals"), (Location, "@class_keyword_loc"), (Location, "@operator_loc"), (Node, "@expression"), (OptNode, "@body"), (Location, "@end_keyword_loc")] },
    // 136
    NodeSpec { name: "SourceEncodingNode", skip_uint32: false, fields: &[] },
    // 137
    NodeSpec { name: "SourceFileNode", skip_uint32: false, fields: &[(Str, "@filepath")] },
    // 138
    NodeSpec { name: "SourceLineNode", skip_uint32: false, fields: &[] },
    // 139
    NodeSpec { name: "SplatNode", skip_uint32: false, fields: &[(Location, "@operator_loc"), (OptNode, "@expression")] },
    // 140
    NodeSpec { name: "StatementsNode", skip_uint32: false, fields: &[(NodeList, "@body")] },
    // 141
    NodeSpec { name: "StringNode", skip_uint32: false, fields: &[(OptLocation, "@opening_loc"), (Location, "@content_loc"), (OptLocation, "@closing_loc"), (Str, "@unescaped")] },
    // 142
    NodeSpec { name: "SuperNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (OptLocation, "@lparen_loc"), (OptNode, "@arguments"), (OptLocation, "@rparen_loc"), (OptNode, "@block")] },
    // 143
    NodeSpec { name: "SymbolNode", skip_uint32: false, fields: &[(OptLocation, "@opening_loc"), (OptLocation, "@value_loc"), (OptLocation, "@closing_loc"), (Str, "@unescaped")] },
    // 144
    NodeSpec { name: "TrueNode", skip_uint32: false, fields: &[] },
    // 145
    NodeSpec { name: "UndefNode", skip_uint32: false, fields: &[(NodeList, "@names"), (Location, "@keyword_loc")] },
    // 146
    NodeSpec { name: "UnlessNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (Node, "@predicate"), (OptLocation, "@then_keyword_loc"), (OptNode, "@statements"), (OptNode, "@else_clause"), (OptLocation, "@end_keyword_loc")] },
    // 147
    NodeSpec { name: "UntilNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (OptLocation, "@do_keyword_loc"), (OptLocation, "@closing_loc"), (Node, "@predicate"), (OptNode, "@statements")] },
    // 148
    NodeSpec { name: "WhenNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (NodeList, "@conditions"), (OptLocation, "@then_keyword_loc"), (OptNode, "@statements")] },
    // 149
    NodeSpec { name: "WhileNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (OptLocation, "@do_keyword_loc"), (OptLocation, "@closing_loc"), (Node, "@predicate"), (OptNode, "@statements")] },
    // 150
    NodeSpec { name: "XStringNode", skip_uint32: false, fields: &[(Location, "@opening_loc"), (Location, "@content_loc"), (Location, "@closing_loc"), (Str, "@unescaped")] },
    // 151
    NodeSpec { name: "YieldNode", skip_uint32: false, fields: &[(Location, "@keyword_loc"), (OptLocation, "@lparen_loc"), (OptNode, "@arguments"), (OptLocation, "@rparen_loc")] },
];

/// Wire token-type table; index 0 is the end-of-tokens terminator.
pub(crate) static TOKEN_TYPES: [&str; 165] = [
    "",
    "EOF",
    "BRACE_RIGHT",
    "COMMA",
    "EMBEXPR_END",
    "KEYWORD_DO",
    "KEYWORD_ELSE",
    "KEYWORD_ELSIF",
    "KEYWORD_END",
    "KEYWORD_ENSURE",
    "KEYWORD_IN",
    "KEYWORD_RESCUE",
    "KEYWORD_THEN",
    "KEYWORD_WHEN",
    "NEWLINE",
    "PARENTHESIS_RIGHT",
    "PIPE",
    "SEMICOLON",
    "AMPERSAND",
    "AMPERSAND_AMPERSAND",
    "AMPERSAND_AMPERSAND_EQUAL",
    "AMPERSAND_DOT",
    "AMPERSAND_EQUAL",
    "BACKTICK",
    "BACK_REFERENCE",
    "BANG",
    "BANG_EQUAL",
    "BANG_TILDE",
    "BRACE_LEFT",
    "BRACKET_LEFT",
    "BRACKET_LEFT_ARRAY",
    "BRACKET_LEFT_RIGHT",
    "BRACKET_LEFT_RIGHT_EQUAL",
    "BRACKET_RIGHT",
    "CARET",
    "CARET_EQUAL",
    "CHARACTER_LITERAL",
    "CLASS_VARIABLE",
    "COLON",
    "COLON_COLON",
    "COMMENT",
    "CONSTANT",
    "DOT",
    "DOT_DOT",
    "DOT_DOT_DOT",
    "EMBDOC_BEGIN",
    "EMBDOC_END",
    "EMBDOC_LINE",
    "EMBEXPR_BEGIN",
    "EMBVAR",
    "EQUAL",
    "EQUAL_EQUAL",
    "EQUAL_EQUAL_EQUAL",
    "EQUAL_GREATER",
    "EQUAL_TILDE",
    "FLOAT",
    "FLOAT_IMAGINARY",
    "FLOAT_RATIONAL",
    "FLOAT_RATIONAL_IMAGINARY",
    "GLOBAL_VARIABLE",
    "GREATER",
    "GREATER_EQUAL",
    "GREATER_GREATER",
    "GREATER_GREATER_EQUAL",
    "HEREDOC_END",
    "HEREDOC_START",
    "IDENTIFIER",
    "IGNORED_NEWLINE",
    "INSTANCE_VARIABLE",
    "INTEGER",
    "INTEGER_IMAGINARY",
    "INTEGER_RATIONAL",
    "INTEGER_RATIONAL_IMAGINARY",
    "KEYWORD_ALIAS",
    "KEYWORD_AND",
    "KEYWORD_BEGIN",
    "KEYWORD_BEGIN_UPCASE",
    "KEYWORD_BREAK",
    "KEYWORD_CASE",
    "KEYWORD_CLASS",
    "KEYWORD_DEF",
    "KEYWORD_DEFINED",
    "KEYWORD_DO_LOOP",
    "KEYWORD_END_UPCASE",
    "KEYWORD_FALSE",
    "KEYWORD_FOR",
    "KEYWORD_IF",
    "KEYWORD_IF_MODIFIER",
    "KEYWORD_MODULE",
    "KEYWORD_NEXT",
    "KEYWORD_NIL",
    "KEYWORD_NOT",
    "KEYWORD_OR",
    "KEYWORD_REDO",
    "KEYWORD_RESCUE_MODIFIER",
    "KEYWORD_RETRY",
    "KEYWORD_RETURN",
    "KEYWORD_SELF",
    "KEYWORD_SUPER",
    "KEYWORD_TRUE",
    "KEYWORD_UNDEF",
    "KEYWORD_UNLESS",
    "KEYWORD_UNLESS_MODIFIER",
    "KEYWORD_UNTIL",
    "KEYWORD_UNTIL_MODIFIER",
    "KEYWORD_WHILE",
    "KEYWORD_WHILE_MODIFIER",
    "KEYWORD_YIELD",
    "KEYWORD___ENCODING__",
    "KEYWORD___FILE__",
    "KEYWORD___LINE__",
    "LABEL",
    "LABEL_END",
    "LAMBDA_BEGIN",
    "LESS",
    "LESS_EQUAL",
    "LESS_EQUAL_GREATER",
    "LESS_LESS",
    "LESS_LESS_EQUAL",
    "METHOD_NAME",
    "MINUS",
    "MINUS_EQUAL",
    "MINUS_GREATER",
    "NUMBERED_REFERENCE",
    "PARENTHESIS_LEFT",
    "PARENTHESIS_LEFT_PARENTHESES",
    "PERCENT",
    "PERCENT_EQUAL",
    "PERCENT_LOWER_I",
    "PERCENT_LOWER_W",
    "PERCENT_LOWER_X",
    "PERCENT_UPPER_I",
    "PERCENT_UPPER_W",
    "PIPE_EQUAL",
    "PIPE_PIPE",
    "PIPE_PIPE_EQUAL",
    "PLUS",
    "PLUS_EQUAL",
    "QUESTION_MARK",
    "REGEXP_BEGIN",
    "REGEXP_END",
    "SLASH",
    "SLASH_EQUAL",
    "STAR",
    "STAR_EQUAL",
    "STAR_STAR",
    "STAR_STAR_EQUAL",
    "STRING_BEGIN",
    "STRING_CONTENT",
    "STRING_END",
    "SYMBOL_BEGIN",
    "TILDE",
    "UAMPERSAND",
    "UCOLON_COLON",
    "UDOT_DOT",
    "UDOT_DOT_DOT",
    "UMINUS",
    "UMINUS_NUM",
    "UPLUS",
    "USTAR",
    "USTAR_STAR",
    "WORDS_SEP",
    "__END__",
    "MISSING",
    "NOT_PROVIDED",
];

/// Diagnostic type symbols, by wire diagnostic id.
pub(crate) static DIAGNOSTIC_TYPES: [&str; 324] = [
    "alias_argument",
    "alias_argument_numbered_reference",
    "ampampeq_multi_assign",
    "argument_after_block",
    "argument_after_forwarding_ellipses",
    "argument_bare_hash",
    "argument_block_forwarding",
    "argument_block_multi",
    "argument_conflict_ampersand",
    "argument_conflict_star",
    "argument_conflict_star_star",
    "argument_formal_class",
    "argument_formal_constant",
    "argument_formal_global",
    "argument_formal_ivar",
    "argument_forwarding_unbound",
    "argument_no_forwarding_ampersand",
    "argument_no_forwarding_ellipses",
    "argument_no_forwarding_star",
    "argument_no_forwarding_star_star",
    "argument_splat_after_assoc_splat",
    "argument_splat_after_splat",
    "argument_term_paren",
    "argument_unexpected_block",
    "array_element",
    "array_expression",
    "array_expression_after_star",
    "array_separator",
    "array_term",
    "begin_lonely_else",
    "begin_term",
    "begin_upcase_brace",
    "begin_upcase_term",
    "begin_upcase_toplevel",
    "block_param_local_variable",
    "block_param_pipe_term",
    "block_term_brace",
    "block_term_end",
    "cannot_parse_expression",
    "cannot_parse_string_part",
    "case_expression_after_case",
    "case_expression_after_when",
    "case_match_missing_predicate",
    "case_missing_conditions",
    "case_term",
    "class_in_method",
    "class_name",
    "class_superclass",
    "class_term",
    "class_unexpected_end",
    "class_variable_bare",
    "conditional_elsif_predicate",
    "conditional_if_predicate",
    "conditional_predicate_term",
    "conditional_term",
    "conditional_term_else",
    "conditional_unless_predicate",
    "conditional_until_predicate",
    "conditional_while_predicate",
    "constant_path_colon_colon_constant",
    "def_endless",
    "def_endless_parameters",
    "def_endless_setter",
    "def_name",
    "def_params_term",
    "def_params_term_paren",
    "def_receiver",
    "def_receiver_term",
    "def_term",
    "defined_expression",
    "embdoc_term",
    "embexpr_end",
    "embvar_invalid",
    "end_upcase_brace",
    "end_upcase_term",
    "escape_invalid_control",
    "escape_invalid_control_repeat",
    "escape_invalid_hexadecimal",
    "escape_invalid_meta",
    "escape_invalid_meta_repeat",
    "escape_invalid_unicode",
    "escape_invalid_unicode_cm_flags",
    "escape_invalid_unicode_list",
    "escape_invalid_unicode_literal",
    "escape_invalid_unicode_long",
    "escape_invalid_unicode_short",
    "escape_invalid_unicode_term",
    "expect_argument",
    "expect_eol_after_statement",
    "expect_expression_after_ampampeq",
    "expect_expression_after_comma",
    "expect_expression_after_equal",
    "expect_expression_after_less_less",
    "expect_expression_after_lparen",
    "expect_expression_after_operator",
    "expect_expression_after_pipepipeeq",
    "expect_expression_after_question",
    "expect_expression_after_splat",
    "expect_expression_after_splat_hash",
    "expect_expression_after_star",
    "expect_for_delimiter",
    "expect_ident_req_parameter",
    "expect_in_delimiter",
    "expect_lparen_after_not_lparen",
    "expect_lparen_after_not_other",
    "expect_lparen_req_parameter",
    "expect_message",
    "expect_rbracket",
    "expect_rparen",
    "expect_rparen_after_multi",
    "expect_rparen_req_parameter",
    "expect_singleton_class_delimiter",
    "expect_string_content",
    "expect_when_delimiter",
    "expression_bare_hash",
    "expression_not_writable",
    "expression_not_writable_encoding",
    "expression_not_writable_false",
    "expression_not_writable_file",
    "expression_not_writable_line",
    "expression_not_writable_nil",
    "expression_not_writable_numbered",
    "expression_not_writable_self",
    "expression_not_writable_true",
    "float_parse",
    "for_collection",
    "for_in",
    "for_index",
    "for_term",
    "global_variable_bare",
    "hash_expression_after_label",
    "hash_key",
    "hash_rocket",
    "hash_term",
    "hash_value",
    "heredoc_identifier",
    "heredoc_term",
    "incomplete_question_mark",
    "incomplete_variable_class",
    "incomplete_variable_class_3_3",
    "incomplete_variable_instance",
    "incomplete_variable_instance_3_3",
    "instance_variable_bare",
    "invalid_block_exit",
    "invalid_character",
    "invalid_comma",
    "invalid_encoding_magic_comment",
    "invalid_escape_character",
    "invalid_float_exponent",
    "invalid_local_variable_read",
    "invalid_local_variable_write",
    "invalid_multibyte_char",
    "invalid_multibyte_character",
    "invalid_multibyte_escape",
    "invalid_number_binary",
    "invalid_number_decimal",
    "invalid_number_fraction",
    "invalid_number_hexadecimal",
    "invalid_number_octal",
    "invalid_number_underscore_inner",
    "invalid_number_underscore_trailing",
    "invalid_percent",
    "invalid_percent_eof",
    "invalid_printable_character",
    "invalid_retry_after_else",
    "invalid_retry_after_ensure",
    "invalid_retry_without_rescue",
    "invalid_symbol",
    "invalid_variable_global",
    "invalid_variable_global_3_3",
    "invalid_yield",
    "it_not_allowed_numbered",
    "it_not_allowed_ordinary",
    "lambda_open",
    "lambda_term_brace",
    "lambda_term_end",
    "list_i_lower_element",
    "list_i_lower_term",
    "list_i_upper_element",
    "list_i_upper_term",
    "list_w_lower_element",
    "list_w_lower_term",
    "list_w_upper_element",
    "list_w_upper_term",
    "malloc_failed",
    "mixed_encoding",
    "module_in_method",
    "module_name",
    "module_term",
    "multi_assign_multi_splats",
    "multi_assign_unexpected_rest",
    "nesting_too_deep",
    "no_local_variable",
    "non_associative_operator",
    "not_expression",
    "number_literal_underscore",
    "numbered_parameter_inner_block",
    "numbered_parameter_it",
    "numbered_parameter_ordinary",
    "numbered_parameter_outer_block",
    "operator_multi_assign",
    "operator_write_arguments",
    "operator_write_block",
    "parameter_assoc_splat_multi",
    "parameter_block_multi",
    "parameter_circular",
    "parameter_forwarding_after_rest",
    "parameter_method_name",
    "parameter_name_duplicated",
    "parameter_no_default",
    "parameter_no_default_kw",
    "parameter_numbered_reserved",
    "parameter_order",
    "parameter_splat_multi",
    "parameter_star",
    "parameter_unexpected_fwd",
    "parameter_unexpected_no_kw",
    "parameter_wild_loose_comma",
    "pattern_array_multiple_rests",
    "pattern_capture_duplicate",
    "pattern_capture_in_alternative",
    "pattern_expression_after_bracket",
    "pattern_expression_after_comma",
    "pattern_expression_after_hrocket",
    "pattern_expression_after_in",
    "pattern_expression_after_key",
    "pattern_expression_after_paren",
    "pattern_expression_after_pin",
    "pattern_expression_after_pipe",
    "pattern_expression_after_range",
    "pattern_expression_after_rest",
    "pattern_find_missing_inner",
    "pattern_hash_implicit",
    "pattern_hash_key",
    "pattern_hash_key_duplicate",
    "pattern_hash_key_interpolated",
    "pattern_hash_key_label",
    "pattern_hash_key_locals",
    "pattern_ident_after_hrocket",
    "pattern_label_after_comma",
    "pattern_rest",
    "pattern_term_brace",
    "pattern_term_bracket",
    "pattern_term_paren",
    "pipepipeeq_multi_assign",
    "regexp_encoding_option_mismatch",
    "regexp_incompat_char_encoding",
    "regexp_invalid_unicode_range",
    "regexp_non_escaped_mbc",
    "regexp_parse_error",
    "regexp_term",
    "regexp_unknown_options",
    "regexp_utf8_char_non_utf8_regexp",
    "rescue_expression",
    "rescue_modifier_value",
    "rescue_term",
    "rescue_variable",
    "return_invalid",
    "script_not_found",
    "singleton_for_literals",
    "statement_alias",
    "statement_postexe_end",
    "statement_preexe_begin",
    "statement_undef",
    "string_concatenation",
    "string_interpolated_term",
    "string_literal_eof",
    "string_literal_term",
    "symbol_invalid",
    "symbol_term_dynamic",
    "symbol_term_interpolated",
    "ternary_colon",
    "ternary_expression_false",
    "ternary_expression_true",
    "unary_disallowed",
    "unary_receiver",
    "undef_argument",
    "unexpected_block_argument",
    "unexpected_index_block",
    "unexpected_index_keywords",
    "unexpected_label",
    "unexpected_multi_write",
    "unexpected_parameter_default_value",
    "unexpected_range_operator",
    "unexpected_safe_navigation",
    "unexpected_token_close_context",
    "unexpected_token_ignore",
    "until_term",
    "void_expression",
    "while_term",
    "write_target_in_method",
    "write_target_readonly",
    "write_target_unexpected",
    "xstring_term",
    "ambiguous_binary_operator",
    "ambiguous_first_argument_minus",
    "ambiguous_first_argument_plus",
    "ambiguous_prefix_ampersand",
    "ambiguous_prefix_star",
    "ambiguous_prefix_star_star",
    "ambiguous_slash",
    "comparison_after_comparison",
    "dot_dot_dot_eol",
    "equal_in_conditional",
    "equal_in_conditional_3_3",
    "end_in_method",
    "duplicated_hash_key",
    "duplicated_when_clause",
    "float_out_of_range",
    "ignored_frozen_string_literal",
    "indentation_mismatch",
    "integer_in_flip_flop",
    "invalid_character",
    "invalid_magic_comment_value",
    "invalid_numbered_reference",
    "keyword_eol",
    "literal_in_condition_default",
    "literal_in_condition_verbose",
    "shareable_constant_value_line",
    "shebang_carriage_return",
    "unexpected_carriage_return",
    "unreachable_statement",
    "unused_local_variable",
    "void_statement",
];
