use std::collections::BTreeSet;
use std::path::PathBuf;

fn main() {
    let target = std::env::var("TARGET").unwrap_or_default();

    // For wasm32-wasip1, Rust std references __wasi_init_tp (thread-pool init)
    // even when we don't use threads. Provide a no-op stub from a tiny C file.
    if target.starts_with("wasm32-wasi") {
        let stub_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("wasi_stub.c");
        std::fs::write(&stub_path, "void __wasi_init_tp(void) {}\n").unwrap();
        cc::Build::new().file(&stub_path).compile("wasi_stub");
    }

    // C-ext compat (spike Level 0): the `rubyrs` binary must export
    // the `rb_*` symbols from `rubyrs-cext` to its dynamic symbol
    // table so dlopen'd C extensions can resolve them at runtime.
    // macOS / Mach-O exports global symbols by default; ELF (Linux,
    // *BSD) needs an explicit `--export-dynamic`.
    if target.contains("linux") || target.contains("freebsd") || target.contains("netbsd") {
        println!("cargo:rustc-link-arg-bin=rubyrs=-Wl,--export-dynamic");
    }

    // --- prism node sets: validate + codegen ---
    emit_prism_node_sets();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/ast.rs");
    println!("cargo:rerun-if-changed=data/supported_prism_nodes.txt");
    println!("cargo:rerun-if-changed=data/rides_along_prism_nodes.txt");
}

fn emit_prism_node_sets() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let supported = parse_node_list(&manifest.join("data/supported_prism_nodes.txt"));
    let rides_along = parse_node_list(&manifest.join("data/rides_along_prism_nodes.txt"));

    // Cross-check 1: SUPPORTED ∩ RIDES_ALONG must be empty.
    let dupes: Vec<_> = supported.intersection(&rides_along).collect();
    assert!(
        dupes.is_empty(),
        "rubyrs: same Prism node listed in both supported and rides_along data files: {dupes:?}"
    );

    // Cross-check 2: every `as_*_node` accessor in ast.rs must be
    // present in SUPPORTED, and vice versa. This is the no-drift
    // guarantee — the const advertised in lib.rs cannot lie.
    let ast_src = std::fs::read_to_string(manifest.join("src/ast.rs"))
        .expect("rubyrs build.rs: cannot read src/ast.rs");
    let accessor_names = extract_as_node_accessors(&ast_src);
    let only_in_data: Vec<_> = supported.difference(&accessor_names).collect();
    let only_in_ast: Vec<_> = accessor_names.difference(&supported).collect();
    assert!(
        only_in_data.is_empty() && only_in_ast.is_empty(),
        "rubyrs build.rs: data/supported_prism_nodes.txt is out of sync with src/ast.rs.\n  \
         Listed in data file but no as_*_node accessor in ast.rs: {only_in_data:?}\n  \
         Used in ast.rs but missing from data file: {only_in_ast:?}"
    );

    // Codegen the two `pub const` arrays into OUT_DIR.
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("prism_node_sets.rs");
    let mut s = String::new();
    s.push_str("// @generated by build.rs from data/*.txt — do not edit.\n\n");
    write_const_array(&mut s, "SUPPORTED_PRISM_NODES", &supported);
    s.push('\n');
    write_const_array(&mut s, "RIDES_ALONG_PRISM_NODES", &rides_along);
    std::fs::write(&out, s).expect("rubyrs build.rs: failed to write generated file");
}

fn parse_node_list(path: &std::path::Path) -> BTreeSet<String> {
    let body = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("rubyrs build.rs: cannot read {}: {e}", path.display()));
    let mut out = BTreeSet::new();
    for (i, raw) in body.lines().enumerate() {
        let line = raw.split('#').next().unwrap().trim();
        if line.is_empty() {
            continue;
        }
        assert!(
            line.chars().next().is_some_and(|c| c.is_ascii_uppercase())
                && line.ends_with("Node")
                && line.chars().all(|c| c.is_ascii_alphanumeric()),
            "rubyrs build.rs: {}:{} — not a valid Prism node name: {line:?}",
            path.display(),
            i + 1
        );
        assert!(
            out.insert(line.to_string()),
            "rubyrs build.rs: {} lists {line:?} twice",
            path.display()
        );
    }
    out
}

/// Extract `as_*_node` accessor calls from ast.rs source and
/// convert each to its Prism CamelCase variant name.
/// `as_constant_path_node` → `ConstantPathNode`.
fn extract_as_node_accessors(src: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for (start, _) in src.match_indices("as_") {
        let tail = &src[start..];
        let end = tail
            .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
            .unwrap_or(tail.len());
        let ident = &tail[..end];
        let Some(stripped) = ident.strip_prefix("as_").and_then(|s| s.strip_suffix("_node")) else {
            continue;
        };
        if stripped.is_empty() {
            continue;
        }
        let mut camel = String::new();
        for part in stripped.split('_') {
            if part.is_empty() {
                continue;
            }
            let mut chars = part.chars();
            camel.push(chars.next().unwrap().to_ascii_uppercase());
            camel.extend(chars);
        }
        camel.push_str("Node");
        out.insert(camel);
    }
    out
}

fn write_const_array(s: &mut String, name: &str, items: &BTreeSet<String>) {
    use std::fmt::Write;
    writeln!(s, "pub const {name}: &[&str] = &[").unwrap();
    for item in items {
        writeln!(s, "    {item:?},").unwrap();
    }
    writeln!(s, "];").unwrap();
}
