//! Golden tests: lex the fixture snippets with the extracted Python table
//! and require BYTE-IDENTICAL HTML to rouge's own output (the
//! `*.expected.html` fixtures are generated by `Rouge::Formatters::HTML`
//! over `Rouge::Lexers::Python` — see `tools/extract.rb`'s header for the
//! regeneration procedure).

use carmine::{html, Lexer, LexerTable, NoCallbacks};

fn table() -> LexerTable {
    let json = include_str!("fixtures/python.json");
    LexerTable::from_json(json).expect("fixture table loads")
}

fn assert_golden(snippet: &str, expected: &str) {
    let table = table();
    let mut lexer = Lexer::new(&table);
    let toks = lexer.lex(snippet, &mut NoCallbacks).expect("lex succeeds without callbacks");
    let got = html::format(&table, &toks);
    assert_eq!(got, expected, "HTML must be byte-identical to rouge");
}

#[test]
fn snippet1_byte_identical_to_rouge() {
    assert_golden(
        include_str!("fixtures/snippet1.py"),
        include_str!("fixtures/snippet1.expected.html"),
    );
}

#[test]
fn snippet2_byte_identical_to_rouge() {
    assert_golden(
        include_str!("fixtures/snippet2.py"),
        include_str!("fixtures/snippet2.expected.html"),
    );
}

#[test]
fn callback_rules_decline_cleanly() {
    // A string literal hits the python string-start rule, which rouge
    // defines with a match-dependent block → carmine marks it
    // `callback`, and NoCallbacks must surface CallbackRequired (the
    // caller's cue to fall back to rouge itself).
    let table = table();
    let mut lexer = Lexer::new(&table);
    let err = lexer.lex("x = 'hi'\n", &mut NoCallbacks).unwrap_err();
    match err {
        carmine::Error::CallbackRequired { state, .. } => assert_eq!(state, "root"),
        other => panic!("expected CallbackRequired, got {other}"),
    }
}

#[test]
fn lexer_is_reusable() {
    let table = table();
    let mut lexer = Lexer::new(&table);
    let a = lexer.lex("def f():\n", &mut NoCallbacks).expect("first lex");
    let b = lexer.lex("def f():\n", &mut NoCallbacks).expect("second lex");
    assert_eq!(a, b);
}

#[test]
fn error_fallback_consumes_unmatchable_input() {
    // U+0000 matches no python rule at the start of an expression
    // context → rouge emits an Error token per char and continues.
    let table = table();
    let mut lexer = Lexer::new(&table);
    let toks = lexer.lex("\u{0}\u{0}x\n", &mut NoCallbacks).expect("lex");
    let names: Vec<&str> = toks.iter().map(|(t, _)| table.token_name(*t)).collect();
    assert!(names.contains(&"Error"), "expected an Error token, got {names:?}");
}
