//! Golden tests: lex the fixture snippets with the extracted Python table
//! and require BYTE-IDENTICAL HTML to rouge's own output (the
//! `*.expected.html` fixtures are generated by `Rouge::Formatters::HTML`
//! over `Rouge::Lexers::Python` — see `tools/extract.rb`'s header for the
//! regeneration procedure).

use carmine::{Lexer, LexerTable, NoCallbacks, html};

fn table() -> LexerTable {
    let json = include_str!("fixtures/python.json");
    LexerTable::from_json(json).expect("fixture table loads")
}

fn assert_golden(snippet: &str, expected: &str) {
    let table = table();
    let mut lexer = Lexer::new(&table);
    let toks = lexer
        .lex(snippet, &mut NoCallbacks)
        .expect("lex succeeds without callbacks");
    let got = html::format(&table, &toks);
    assert_eq!(got, expected, "HTML must be byte-identical to rouge");
}

#[test]
fn snippet1_byte_identical_to_rouge() {
    assert_golden(
        include_str!("fixtures/snippet1.py"),
        include_str!("fixtures/snippet1.expected.html"),
    );
}

#[test]
fn snippet2_byte_identical_to_rouge() {
    assert_golden(
        include_str!("fixtures/snippet2.py"),
        include_str!("fixtures/snippet2.expected.html"),
    );
}

#[test]
fn callback_rules_decline_cleanly() {
    // A string literal hits the python string-start rule, which rouge
    // defines with a match-dependent block → carmine marks it
    // `callback`, and NoCallbacks must surface CallbackRequired (the
    // caller's cue to fall back to rouge itself).
    let table = table();
    let mut lexer = Lexer::new(&table);
    let err = lexer.lex("x = 'hi'\n", &mut NoCallbacks).unwrap_err();
    match err {
        carmine::Error::CallbackRequired { state, .. } => assert_eq!(state, "root"),
        other => panic!("expected CallbackRequired, got {other}"),
    }
}

#[test]
fn lexer_is_reusable() {
    let table = table();
    let mut lexer = Lexer::new(&table);
    let a = lexer
        .lex("def f():\n", &mut NoCallbacks)
        .expect("first lex");
    let b = lexer
        .lex("def f():\n", &mut NoCallbacks)
        .expect("second lex");
    assert_eq!(a, b);
}

#[test]
fn session_callback_roundtrip() {
    // Drive the session API the way an embedder bridging to Ruby would:
    // run() pauses on the string-start callback rule; we replay the DSL
    // effects the original rouge block would produce (Str.Affix +
    // Str.Heredoc groups, push :generic_string) and resume. The
    // generic_string state then hits more callback rules; verify the
    // pause/apply/resume mechanics and the emitted prefix tokens.
    use carmine::{CallbackOp, RunStep};
    let table = table();
    let mut lexer = Lexer::new(&table);
    lexer.begin();
    let text = "x = 'hi'\n";
    let step = lexer.run(text).expect("runs to the string-start callback");
    let (state, groups) = match step {
        RunStep::Callback { state, groups, .. } => (state, groups),
        other => panic!("expected a callback pause, got {other:?}"),
    };
    assert_eq!(state, "root");
    assert_eq!(groups[0].as_deref(), Some("'"));
    // Replay what rouge's block does: groups Str::Affix, Str::Heredoc
    // (affix group is empty here → skipped by yield_token), then push.
    lexer
        .apply_callback_ops(&[
            CallbackOp::Token {
                qualname: "Literal.String.Heredoc".into(),
                value: "'".into(),
            },
            CallbackOp::Push(Some("generic_string".into())),
        ])
        .expect("ops apply");
    // Resume — the next pause (or completion) must come at a LATER
    // position, proving the pending match was consumed.
    match lexer.run(text) {
        Ok(RunStep::Callback { state, .. }) => assert_eq!(state, "generic_string"),
        Ok(RunStep::Done) => {}
        Err(e) => panic!("resume failed: {e}"),
    }
    let toks = lexer.take_tokens();
    let names: Vec<&str> = toks.iter().map(|(t, _)| table.token_name(*t)).collect();
    assert!(
        names.contains(&"Literal.String.Heredoc"),
        "heredoc emitted: {names:?}"
    );
}

#[test]
fn registry_tokens_resolvable_for_callbacks() {
    // The full shortname registry is interned, so a callback can emit a
    // token no rule references; rule_emits stays scoped to rules.
    let table = table();
    assert!(table.token_id("Keyword.Type").is_some());
    assert!(!table.rule_emits("Keyword.Type"));
    assert!(table.rule_emits("Keyword"));
    // The Escape-policy probe: python's rules never emit it.
    assert!(!table.rule_emits("Escape"));
}

#[test]
fn error_fallback_in_callback_free_state() {
    // Unmatchable input in a state with NO callback rule → rouge emits an
    // Error token per char; carmine reproduces it (the fallback is only
    // suppressed when a callback rule is present — see the next test).
    let json = r##"{
      "lexer": "errdemo",
      "states": {"root": [
        {"kind": "tok", "re": "x", "opts": 0, "tok": "Name", "next": null}
      ]},
      "shortnames": {"Name": "n", "Error": "err"}
    }"##;
    let table = LexerTable::from_json(json).expect("table");
    let mut lexer = Lexer::new(&table);
    let toks = lexer.lex("\u{0}\u{0}x\n", &mut NoCallbacks).expect("lex");
    let names: Vec<&str> = toks.iter().map(|(t, _)| table.token_name(*t)).collect();
    assert!(names.contains(&"Error"), "expected Error, got {names:?}");
}

#[test]
fn unmatchable_input_in_callback_state_declines() {
    // python's root carries a callback rule (the string-start). When NO
    // rule matches (U+0000), carmine can't be sure rouge wouldn't have
    // matched via the callback, so it DECLINES rather than risk a wrong
    // Error token — the drop-in "never wrong, only fall back" contract.
    let table = table();
    let mut lexer = Lexer::new(&table);
    match lexer.lex("\u{0}\u{0}x\n", &mut NoCallbacks) {
        Err(carmine::Error::CallbackRequired { .. }) => {}
        other => panic!("expected CallbackRequired decline, got {other:?}"),
    }
}

/// Case-fold classifier condition — `SET.include?(m[0].upcase)` folds the
/// captured group before membership, so a case-insensitive keyword set
/// (SQL/COBOL-style) classifies regardless of the source's case.
#[test]
fn ir_case_fold_condition() {
    let json = r##"{
      "lexer": "cifold",
      "states": {"root": [
        {"kind": "ir", "re": "[a-zA-Z]+", "opts": 0, "ops": [
          ["if", ["ginf", 0, "up", ["SELECT", "FROM"]],
            [["token", "Keyword"]], [["token", "Name"]]]
        ]},
        {"kind": "tok", "re": "\\s+", "opts": 0, "tok": "Text", "next": null}
      ]},
      "shortnames": {"Keyword": "k", "Name": "n", "Text": ""}
    }"##;
    let table = LexerTable::from_json(json).expect("ci-fold table compiles");
    let mut lexer = Lexer::new(&table);
    let toks = lexer.lex("select Foo", &mut NoCallbacks).expect("lex");
    let names: Vec<&str> = table.token_names().collect();
    let rendered: Vec<(String, String)> = toks
        .iter()
        .map(|(t, v)| (names[t.0 as usize].to_string(), v.clone()))
        .collect();
    assert_eq!(
        rendered,
        vec![
            // "select".upcase == "SELECT" ∈ set → Keyword
            ("Keyword".to_string(), "select".to_string()),
            ("Text".to_string(), " ".to_string()),
            // "Foo".upcase == "FOO" ∉ set → Name
            ("Name".to_string(), "Foo".to_string()),
        ]
    );
}

/// `recurse` — re-lex a captured substring with the same table from a
/// fresh :root and splice the tokens in (rouge's `recurse`/`delegate
/// self.class`). The inner digits re-lex as Number; if they couldn't be
/// lexed natively the recurse would propagate a decline.
#[test]
fn ir_recurse_self() {
    let json = r##"{
      "lexer": "recdemo",
      "states": {"root": [
        {"kind": "ir", "re": "\\[([0-9 ]+)\\]", "opts": 0, "ops": [
          ["token", "Punctuation", ["lit", "["]],
          ["recurse", ["g", 1]],
          ["token", "Punctuation", ["lit", "]"]]
        ]},
        {"kind": "tok", "re": "[0-9]+", "opts": 0, "tok": "Literal.Number", "next": null},
        {"kind": "tok", "re": "\\s+", "opts": 0, "tok": "Text", "next": null}
      ]},
      "shortnames": {"Punctuation": "p", "Literal.Number": "m", "Text": ""}
    }"##;
    let table = LexerTable::from_json(json).expect("recurse table compiles");
    let mut lexer = Lexer::new(&table);
    let toks = lexer.lex("[4 2]", &mut NoCallbacks).expect("recurse lex");
    let names: Vec<&str> = table.token_names().collect();
    let rendered: Vec<(String, String)> = toks
        .iter()
        .map(|(t, v)| (names[t.0 as usize].to_string(), v.clone()))
        .collect();
    assert_eq!(
        rendered,
        vec![
            ("Punctuation".to_string(), "[".to_string()),
            // "4 2" re-lexed by the same table: Number, Text, Number
            ("Literal.Number".to_string(), "4".to_string()),
            ("Text".to_string(), " ".to_string()),
            ("Literal.Number".to_string(), "2".to_string()),
            ("Punctuation".to_string(), "]".to_string()),
        ]
    );
}

/// Conditional Action IR — a hand-written table exercising the op/
/// expr/cond vocabulary end to end (Track C-1 engine side).
#[test]
fn ir_rule_execution() {
    let json = r##"{
      "lexer": "irdemo",
      "states": {
        "root": [
          {"kind": "ir", "re": "(<<[-~]?)([A-Z]+)", "opts": 0, "ops": [
            ["token", "Operator", ["g", 1]],
            ["token", "Name.Constant", ["cat", ["g", 2], ["lit", "!"]]],
            ["lpush", "queue", [["gin", 1, ["<<-", "<<~"]], ["g", 2]]],
            ["if", ["not", ["instate", "heredoc"]], [["push", "heredoc"]], []]
          ]},
          {"kind": "tok", "re": "\\s+", "opts": 0, "tok": "Text", "next": null}
        ],
        "heredoc": [
          {"kind": "ir", "re": "x", "opts": 0, "ops": [
            ["if", ["ivar", "queue"], [["token", "Keyword"], ["pop", 1]], [["token", "Error"]]]
          ]},
          {"kind": "tok", "re": "\\s+", "opts": 0, "tok": "Text", "next": null}
        ]
      },
      "shortnames": {"Operator": "o", "Name.Constant": "no", "Text": "", "Keyword": "k", "Error": "err"}
    }"##;
    let table = LexerTable::from_json(json).expect("ir table compiles");
    let mut lexer = Lexer::new(&table);
    let toks = lexer.lex("<<~EOF x", &mut NoCallbacks).expect("ir lex");
    let names: Vec<&str> = table.token_names().collect();
    let rendered: Vec<(String, String)> = toks
        .iter()
        .map(|(t, v)| (names[t.0 as usize].to_string(), v.clone()))
        .collect();
    assert_eq!(
        rendered,
        vec![
            ("Operator".to_string(), "<<~".to_string()),
            ("Name.Constant".to_string(), "EOF!".to_string()),
            ("Text".to_string(), " ".to_string()),
            // inside :heredoc, queue ivar is truthy → Keyword + pop
            ("Keyword".to_string(), "x".to_string()),
        ]
    );
}
