//! Compile-time wiring for gapscan.
//!
//! 1. Reads `data/prism_node_classes.txt` (the canonical list of every
//!    Prism AST node class — 151 of them today). This file lives in
//!    THIS crate; no cross-crate dependency.
//! 2. Generates the `ALL_PRISM_NODES` const and the
//!    `impl_full_visit_for!` macro, which produces a 151-arm
//!    `impl ruby_prism::Visit` for `Histogrammer`. The macro is the
//!    only way to surface every node class — relying on the default
//!    `visit_branch_node_enter` hook silently skips wrapper nodes
//!    that parents reach via specialised `visit_X_node(&X)` calls
//!    (ArgumentsNode, RescueNode, etc.).
//!
//! Classification (Supported / RidesAlong / Missing) is **not**
//! generated here. It lives in lib.rs as a `LazyLock<HashSet<&str>>`
//! built from `rubyrs::SUPPORTED_PRISM_NODES` /
//! `rubyrs::RIDES_ALONG_PRISM_NODES` at first use. This deliberately
//! avoids reading sibling-crate data files at build time — which is
//! not a Cargo-supported pattern (sibling paths do not survive
//! `cargo publish` tarball boundaries) and which is not necessary
//! since rubyrs already publishes the data as a `pub const`.
//!
//! Fixture-annotation validation (the previous build.rs's
//! `# ClassName (× N)` tripwire) moved to `tests/scan.rs` where it
//! has runtime access to the same `classify()` it's guarding.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let prism_all = parse_node_list(&manifest.join("data/prism_node_classes.txt"));

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("prism_codegen.rs");
    let mut s = String::new();
    s.push_str("// @generated by build.rs — do not edit.\n\n");
    write_const_array(&mut s, "ALL_PRISM_NODES", &prism_all);
    s.push('\n');
    write_full_visit_macro(&mut s, &prism_all);
    std::fs::write(&out, s).expect("rubyrs-gapscan build.rs: write failed");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data/prism_node_classes.txt");
}

fn parse_node_list(path: &Path) -> BTreeSet<String> {
    let body = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("rubyrs-gapscan build.rs: cannot read {}: {e}", path.display()));
    let mut out = BTreeSet::new();
    for (i, raw) in body.lines().enumerate() {
        let line = raw.split('#').next().unwrap().trim();
        if line.is_empty() {
            continue;
        }
        assert!(
            line.chars().next().is_some_and(|c| c.is_ascii_uppercase())
                && line.ends_with("Node")
                && line.chars().all(|c| c.is_ascii_alphanumeric()),
            "rubyrs-gapscan build.rs: {}:{} — not a valid Prism node name: {line:?}",
            path.display(),
            i + 1
        );
        assert!(
            out.insert(line.to_string()),
            "rubyrs-gapscan build.rs: {} lists {line:?} twice",
            path.display()
        );
    }
    out
}

fn write_const_array(s: &mut String, name: &str, items: &BTreeSet<String>) {
    use std::fmt::Write;
    writeln!(s, "pub const {name}: &[&str] = &[").unwrap();
    for item in items {
        writeln!(s, "    {item:?},").unwrap();
    }
    writeln!(s, "];").unwrap();
}

/// Generate `impl_full_visit_for!(SomeType)` macro that emits an
/// `impl ruby_prism::Visit` block with all 151 `visit_*_node` methods
/// overridden. ruby-prism's default `visit()` does NOT call
/// `visit_branch_node_enter` for wrapper nodes that parents reach via
/// the specialized `visit_X_node(&X)` path (e.g. `ArgumentsNode`,
/// `RescueNode`), so the only way to get a complete histogram is to
/// override every typed visitor. The target type must expose a
/// `record(&mut self, class: &'static str, node: &ruby_prism::Node)`
/// method.
fn write_full_visit_macro(s: &mut String, all: &BTreeSet<String>) {
    use std::fmt::Write;
    // No `#[macro_export]`: the macro is an internal codegen detail
    // for `Histogrammer`'s Visit impl. Because the generated file is
    // `include!`-d at the crate root in src/lib.rs, the macro lives
    // in the same module as its sole caller and is usable without
    // export. Keeping it unexported avoids committing it to the
    // public API surface of this crate.
    s.push_str(
        "macro_rules! impl_full_visit_for {\n    \
             ($t:ty) => {\n        \
                 impl<'pr> ruby_prism::Visit<'pr> for $t {\n",
    );
    for class in all {
        let snake = camel_to_snake(class);
        let extra = extra_hook(class).unwrap_or("");
        writeln!(
            s,
            "            fn visit_{snake}(&mut self, node: &ruby_prism::{class}<'pr>) {{\n                \
                 self.record({class:?}, &node.as_node());\n{extra}                \
                 ruby_prism::visit_{snake}(self, node);\n            \
             }}"
        )
        .unwrap();
    }
    s.push_str("        }\n    };\n}\n");
}

/// Extra Rust statement(s) to inject into the generated `visit_X_node`
/// arm, in addition to the standard `record(class, node)` call.
/// The target type must implement the methods named here. Each
/// entry must end with a trailing newline so the generated source
/// stays readable.
fn extra_hook(class: &str) -> Option<&'static str> {
    match class {
        "CallNode" => Some("                self.record_call(node);\n"),
        _ => None,
    }
}

fn camel_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for (i, c) in s.char_indices() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
