//! Compile-time wiring for gapscan.
//!
//! 1. Reads `data/prism_node_classes.txt` (the canonical list of every
//!    Prism AST node class — 151 of them today).
//! 2. Reads rubyrs's own data files (the SUPPORTED + RIDES_ALONG sets
//!    that lib.rs re-exports) and asserts both sit inside the Prism
//!    universe. Catches any rename/removal when Prism upgrades.
//! 3. Generates the `ALL_PRISM_NODES` const and the
//!    `impl_full_visit_for!` macro, which produces a 151-arm
//!    `impl ruby_prism::Visit` for `Histogrammer`. The macro is the
//!    only way to surface every node class — relying on the default
//!    `visit_branch_node_enter` hook silently skips wrapper nodes
//!    that parents reach via specialised `visit_X_node(&X)` calls
//!    (ArgumentsNode, RescueNode, etc.).

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    let prism_all = parse_node_list(&manifest.join("data/prism_node_classes.txt"));

    // rubyrs/data/*.txt is the single source of truth — same file the
    // rubyrs crate's own build.rs reads. We re-read it here (rather
    // than pulling the const through a build-dep) to keep gapscan's
    // build cheap.
    let rubyrs_data = manifest.join("../rubyrs/data");
    let supported = parse_node_list(&rubyrs_data.join("supported_prism_nodes.txt"));
    let rides_along = parse_node_list(&rubyrs_data.join("rides_along_prism_nodes.txt"));

    let unknown_supported: Vec<_> = supported.difference(&prism_all).collect();
    let unknown_rides_along: Vec<_> = rides_along.difference(&prism_all).collect();
    assert!(
        unknown_supported.is_empty() && unknown_rides_along.is_empty(),
        "rubyrs-gapscan: rubyrs claims to handle Prism node(s) that don't exist in \
         data/prism_node_classes.txt — Prism likely renamed or removed them. \
         Refresh data/prism_node_classes.txt and reconcile.\n  \
         Unknown in supported: {unknown_supported:?}\n  \
         Unknown in rides_along: {unknown_rides_along:?}"
    );

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("prism_codegen.rs");
    let mut s = String::new();
    s.push_str("// @generated by build.rs — do not edit.\n\n");
    write_const_array(&mut s, "ALL_PRISM_NODES", &prism_all);
    s.push('\n');
    write_classify_fn(&mut s, &prism_all, &supported, &rides_along);
    s.push('\n');
    write_full_visit_macro(&mut s, &prism_all);
    std::fs::write(&out, s).expect("rubyrs-gapscan build.rs: write failed");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data/prism_node_classes.txt");
    println!("cargo:rerun-if-changed=../rubyrs/data/supported_prism_nodes.txt");
    println!("cargo:rerun-if-changed=../rubyrs/data/rides_along_prism_nodes.txt");
}

fn parse_node_list(path: &Path) -> BTreeSet<String> {
    let body = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("rubyrs-gapscan build.rs: cannot read {}: {e}", path.display()));
    let mut out = BTreeSet::new();
    for (i, raw) in body.lines().enumerate() {
        let line = raw.split('#').next().unwrap().trim();
        if line.is_empty() {
            continue;
        }
        assert!(
            line.chars().next().is_some_and(|c| c.is_ascii_uppercase())
                && line.ends_with("Node")
                && line.chars().all(|c| c.is_ascii_alphanumeric()),
            "rubyrs-gapscan build.rs: {}:{} — not a valid Prism node name: {line:?}",
            path.display(),
            i + 1
        );
        assert!(
            out.insert(line.to_string()),
            "rubyrs-gapscan build.rs: {} lists {line:?} twice",
            path.display()
        );
    }
    out
}

/// Codegen `pub fn classify(name: &str) -> Classification` as a
/// single 151-arm match. Replaces the previous runtime
/// `slice.contains()` lookups which were O(n) per node call (Jekyll:
/// 25k nodes × ~50 SUPPORTED entries ≈ 1.25M comparisons per scan).
/// Now compiles to a perfect-hash-ish jump table — O(1) per call.
///
/// Names not in either rubyrs data file fall through to the `_ =>
/// Missing` arm, so unknown / not-yet-supported Prism node classes
/// keep their existing semantics.
fn write_classify_fn(
    s: &mut String,
    all: &BTreeSet<String>,
    supported: &BTreeSet<String>,
    rides_along: &BTreeSet<String>,
) {
    use std::fmt::Write;
    s.push_str(
        "/// Static lookup: how does `name` (a Prism class name) classify?\n\
         /// Generated from rubyrs/data/*.txt by build.rs — O(1).\n\
         pub fn classify(name: &str) -> crate::Classification {\n    \
             use crate::Classification::*;\n    \
             match name {\n",
    );
    for n in all {
        let cls = if supported.contains(n) {
            "Supported"
        } else if rides_along.contains(n) {
            "RidesAlong"
        } else {
            // Skip explicit arm — falls into the catch-all below.
            continue;
        };
        writeln!(s, "        {n:?} => {cls},").unwrap();
    }
    s.push_str("        _ => Missing,\n    }\n}\n");
}

fn write_const_array(s: &mut String, name: &str, items: &BTreeSet<String>) {
    use std::fmt::Write;
    writeln!(s, "pub const {name}: &[&str] = &[").unwrap();
    for item in items {
        writeln!(s, "    {item:?},").unwrap();
    }
    writeln!(s, "];").unwrap();
}

/// Generate `impl_full_visit_for!(SomeType)` macro that emits an
/// `impl ruby_prism::Visit` block with all 151 `visit_*_node` methods
/// overridden. ruby-prism's default `visit()` does NOT call
/// `visit_branch_node_enter` for wrapper nodes that parents reach via
/// the specialized `visit_X_node(&X)` path (e.g. `ArgumentsNode`,
/// `RescueNode`), so the only way to get a complete histogram is to
/// override every typed visitor. The target type must expose a
/// `record(&mut self, class: &'static str, node: &ruby_prism::Node)`
/// method.
fn write_full_visit_macro(s: &mut String, all: &BTreeSet<String>) {
    use std::fmt::Write;
    // No `#[macro_export]`: the macro is an internal codegen detail
    // for `Histogrammer`'s Visit impl. Because the generated file is
    // `include!`-d at the crate root in src/lib.rs, the macro lives
    // in the same module as its sole caller and is usable without
    // export. Keeping it unexported avoids committing it to the
    // public API surface of this crate.
    s.push_str(
        "macro_rules! impl_full_visit_for {\n    \
             ($t:ty) => {\n        \
                 impl<'pr> ruby_prism::Visit<'pr> for $t {\n",
    );
    for class in all {
        let snake = camel_to_snake(class);
        let extra = extra_hook(class).unwrap_or("");
        writeln!(
            s,
            "            fn visit_{snake}(&mut self, node: &ruby_prism::{class}<'pr>) {{\n                \
                 self.record({class:?}, &node.as_node());\n{extra}                \
                 ruby_prism::visit_{snake}(self, node);\n            \
             }}"
        )
        .unwrap();
    }
    s.push_str("        }\n    };\n}\n");
}

/// Extra Rust statement(s) to inject into the generated `visit_X_node`
/// arm, in addition to the standard `record(class, node)` call.
/// The target type must implement the methods named here. Each
/// entry must end with a trailing newline so the generated source
/// stays readable.
fn extra_hook(class: &str) -> Option<&'static str> {
    match class {
        "CallNode" => Some("                self.record_call(node);\n"),
        _ => None,
    }
}

fn camel_to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for (i, c) in s.char_indices() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

