# frozen_string_literal: true

require "rouge"

module Blusher
  # The rouge-API drop-in: route every `RegexLexer#lex` through carmine when a
  # table exists AND carmine handles the input natively; otherwise fall back to
  # rouge unchanged. Zero-divergence by construction — carmine either returns a
  # byte-identical token stream or declines.
  module Shim
    # qualified rouge token name ("Name.Builtin") → the Token object.
    QUALNAME = {}
    Rouge::Token.each_token { |t| QUALNAME[t.qualname] = t }
    QUALNAME.freeze

    @dir = File.expand_path("tables", __dir__)
    @cache = {}

    class << self
      # Directory of per-lexer carmine tables (`<tag>.json`). Generated by
      # `rake tables` (carmine's tools/extract.rb over the installed rouge).
      attr_accessor :dir

      def table_for(tag)
        return @cache[tag] if @cache.key?(tag)
        path = File.join(@dir, "#{tag}.json")
        @cache[tag] = (File.read(path) if File.exist?(path))
      end

      # Convert carmine's [name, value] pairs to rouge [Token, value] pairs.
      def to_rouge(tokens)
        tokens.map { |name, val| [QUALNAME[name] || Rouge::Token::Tokens::Error, val] }
      end
    end
  end
end

module Rouge
  class RegexLexer
    # Install once (idempotent if the gem is required twice).
    unless method_defined?(:__blusher_rouge_lex)
      alias_method :__blusher_rouge_lex, :lex

      def lex(string, opts = nil, &b)
        table = Blusher::Shim.table_for(self.class.tag)
        if table
          result = Blusher::Native.lex(table, string)
          if result["status"] == "ok"
            toks = Blusher::Shim.to_rouge(result["tokens"])
            return b ? toks.each(&b) : toks.each
          end
        end
        __blusher_rouge_lex(string, opts, &b)
      end
    end
  end
end
