# Generate crates/rubyrs/src/prism_wq/ids.rs from the prism gem's GENERATED
# serialize.rb + node.rb (whitequark-translation port — see prism_wq/mod.rs).
#
# The native whitequark translation decodes the prism wire blob into a generic
# per-node field vector (prism_wq::PNode). The compiler port accesses fields
# positionally; this script pins NAMED constants for every node type id and
# every field index so the port can never drift from the wire order by a
# hand-counted index. Same single-source-of-truth rationale as
# gen_prism_node_specs.rb (whose parsing this reuses): both the wire format
# and the field names are code-generated inside prism from config.yml, so the
# gem's own generated output is the spec.
#
# Usage: ruby scripts/gen_prism_wq_ids.rb [prism_gem_lib_dir]
# Re-run when bumping the linked prism version; the output is checked in.

gem_lib = ARGV[0] || "/Users/linyiru/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/prism-1.9.0/lib"
serialize = File.read(File.join(gem_lib, "prism/serialize.rb"))
node_rb = File.read(File.join(gem_lib, "prism/node.rb"))

major = serialize[/MAJOR_VERSION = (\d+)/, 1] or abort "no MAJOR_VERSION"
minor = serialize[/MINOR_VERSION = (\d+)/, 1] or abort "no MINOR_VERSION"
patch = serialize[/PATCH_VERSION = (\d+)/, 1] or abort "no PATCH_VERSION"

ivars = {}
node_rb.scan(/class (\w+) < Node\b.*?def initialize\(([^)]*)\)/m) do |klass, params|
  names = params.split(",").map(&:strip)
  raise "unexpected initialize prefix for #{klass}" unless names[0, 4] == %w[source node_id location flags]
  ivars[klass] = names[4..]
end

ruby_branch = serialize[/if RUBY_ENGINE == "ruby"\n(.*?)\n\s*else\n/m, 1] or abort "no ruby branch"

def split_args(s)
  args, depth, cur = [], 0, +""
  s.each_char do |c|
    case c
    when "(", "{", "[" then depth += 1; cur << c
    when ")", "}", "]" then depth -= 1; cur << c
    when ","
      if depth.zero?
        args << cur.strip
        cur = +""
      else
        cur << c
      end
    else cur << c
    end
  end
  args << cur.strip unless cur.strip.empty?
  args
end

specs = {} # id => [klass, field names]
ruby_branch.scan(/when (\d+) then\n(.*?)(?=\n\s*when \d+ then\n|\n\s*end\n)/m) do |id, body|
  id = Integer(id)
  m = body.match(/(\w+)\.new\((.*)\)\s*\z/m) or raise "no ctor in when #{id}"
  klass = m[1]
  args = split_args(m[2])
  fields = args[4..]
  names = ivars.fetch(klass)
  raise "count mismatch #{klass}" unless names.length == fields.length
  specs[id] = [klass, names]
end

def snake(klass)
  klass.gsub(/([a-z0-9])([A-Z])/, '\1_\2').downcase
end

out = +""
out << <<~HEADER
  //! GENERATED by scripts/gen_prism_wq_ids.rb from the prism gem's own
  //! generated serialize.rb + node.rb (prism #{major}.#{minor}.#{patch}). Do not edit by
  //! hand — re-run the script when the linked prism version changes.
  //!
  //! Node-type ids (`nt::*`, the 1-based wire type byte) and per-type field
  //! index constants (one module per node type, named after the gem's ivar
  //! names in wire order) for the generic `PNode` field vector.

  #![allow(dead_code)]

HEADER

out << "pub(crate) mod nt {\n"
specs.keys.sort.each do |id|
  klass, = specs[id]
  out << "    pub(crate) const #{snake(klass).upcase}: u8 = #{id};\n"
end
out << "}\n\n"

specs.keys.sort.each do |id|
  klass, names = specs[id]
  next if names.empty?
  out << "pub(crate) mod #{snake(klass)} {\n"
  names.each_with_index do |name, i|
    out << "    pub(crate) const #{name.upcase}: usize = #{i};\n"
  end
  out << "}\n"
end

path = File.expand_path("../crates/rubyrs/src/prism_wq/ids.rs", __dir__)
require "fileutils"
FileUtils.mkdir_p(File.dirname(path))
File.write(path, out)
puts "wrote #{path}: #{specs.length} node types"
