# compat.rb — the ONE runtime-aware file for the AS-lite spike.
#
# On CRuby: load `active_support/all` so the spike has the full
# Rails-shaped behaviour to compare against. The spike's GAPS.md
# is generated by diffing what CRuby+AS produces vs what rubyrs
# produces with its stock surface (no `active_support_lite.rb`
# canon yet — the spike's whole point is to figure out what that
# canon needs to include).
#
# On rubyrs: no-op. Touching any AS method should raise
# NoMethodError; the spike wraps every probe in begin/rescue so
# the script runs to completion and produces a full gap report
# instead of dying on the first miss.
#
# Discriminator: `defined?(RUBYRS)` (ADR 0026 v2 M27 B2 sentinel
# constant). Both runtimes carry `RUBY_ENGINE == "ruby"` so we
# can't use that.

if defined?(RUBYRS)
  RUNTIME_LABEL = "rubyrs (no canon)"
else
  require "active_support/all"
  RUNTIME_LABEL = "CRuby + ActiveSupport #{ActiveSupport::VERSION::STRING}"
end
