//! GENERATED by scripts/gen_prism_wq_ids.rb from the prism gem's own
//! generated serialize.rb + node.rb (prism 1.9.0). Do not edit by
//! hand — re-run the script when the linked prism version changes.
//!
//! Node-type ids (`nt::*`, the 1-based wire type byte) and per-type field
//! index constants (one module per node type, named after the gem's ivar
//! names in wire order) for the generic `PNode` field vector.

#![allow(dead_code)]

pub(crate) mod nt {
    pub(crate) const ALIAS_GLOBAL_VARIABLE_NODE: u8 = 1;
    pub(crate) const ALIAS_METHOD_NODE: u8 = 2;
    pub(crate) const ALTERNATION_PATTERN_NODE: u8 = 3;
    pub(crate) const AND_NODE: u8 = 4;
    pub(crate) const ARGUMENTS_NODE: u8 = 5;
    pub(crate) const ARRAY_NODE: u8 = 6;
    pub(crate) const ARRAY_PATTERN_NODE: u8 = 7;
    pub(crate) const ASSOC_NODE: u8 = 8;
    pub(crate) const ASSOC_SPLAT_NODE: u8 = 9;
    pub(crate) const BACK_REFERENCE_READ_NODE: u8 = 10;
    pub(crate) const BEGIN_NODE: u8 = 11;
    pub(crate) const BLOCK_ARGUMENT_NODE: u8 = 12;
    pub(crate) const BLOCK_LOCAL_VARIABLE_NODE: u8 = 13;
    pub(crate) const BLOCK_NODE: u8 = 14;
    pub(crate) const BLOCK_PARAMETER_NODE: u8 = 15;
    pub(crate) const BLOCK_PARAMETERS_NODE: u8 = 16;
    pub(crate) const BREAK_NODE: u8 = 17;
    pub(crate) const CALL_AND_WRITE_NODE: u8 = 18;
    pub(crate) const CALL_NODE: u8 = 19;
    pub(crate) const CALL_OPERATOR_WRITE_NODE: u8 = 20;
    pub(crate) const CALL_OR_WRITE_NODE: u8 = 21;
    pub(crate) const CALL_TARGET_NODE: u8 = 22;
    pub(crate) const CAPTURE_PATTERN_NODE: u8 = 23;
    pub(crate) const CASE_MATCH_NODE: u8 = 24;
    pub(crate) const CASE_NODE: u8 = 25;
    pub(crate) const CLASS_NODE: u8 = 26;
    pub(crate) const CLASS_VARIABLE_AND_WRITE_NODE: u8 = 27;
    pub(crate) const CLASS_VARIABLE_OPERATOR_WRITE_NODE: u8 = 28;
    pub(crate) const CLASS_VARIABLE_OR_WRITE_NODE: u8 = 29;
    pub(crate) const CLASS_VARIABLE_READ_NODE: u8 = 30;
    pub(crate) const CLASS_VARIABLE_TARGET_NODE: u8 = 31;
    pub(crate) const CLASS_VARIABLE_WRITE_NODE: u8 = 32;
    pub(crate) const CONSTANT_AND_WRITE_NODE: u8 = 33;
    pub(crate) const CONSTANT_OPERATOR_WRITE_NODE: u8 = 34;
    pub(crate) const CONSTANT_OR_WRITE_NODE: u8 = 35;
    pub(crate) const CONSTANT_PATH_AND_WRITE_NODE: u8 = 36;
    pub(crate) const CONSTANT_PATH_NODE: u8 = 37;
    pub(crate) const CONSTANT_PATH_OPERATOR_WRITE_NODE: u8 = 38;
    pub(crate) const CONSTANT_PATH_OR_WRITE_NODE: u8 = 39;
    pub(crate) const CONSTANT_PATH_TARGET_NODE: u8 = 40;
    pub(crate) const CONSTANT_PATH_WRITE_NODE: u8 = 41;
    pub(crate) const CONSTANT_READ_NODE: u8 = 42;
    pub(crate) const CONSTANT_TARGET_NODE: u8 = 43;
    pub(crate) const CONSTANT_WRITE_NODE: u8 = 44;
    pub(crate) const DEF_NODE: u8 = 45;
    pub(crate) const DEFINED_NODE: u8 = 46;
    pub(crate) const ELSE_NODE: u8 = 47;
    pub(crate) const EMBEDDED_STATEMENTS_NODE: u8 = 48;
    pub(crate) const EMBEDDED_VARIABLE_NODE: u8 = 49;
    pub(crate) const ENSURE_NODE: u8 = 50;
    pub(crate) const FALSE_NODE: u8 = 51;
    pub(crate) const FIND_PATTERN_NODE: u8 = 52;
    pub(crate) const FLIP_FLOP_NODE: u8 = 53;
    pub(crate) const FLOAT_NODE: u8 = 54;
    pub(crate) const FOR_NODE: u8 = 55;
    pub(crate) const FORWARDING_ARGUMENTS_NODE: u8 = 56;
    pub(crate) const FORWARDING_PARAMETER_NODE: u8 = 57;
    pub(crate) const FORWARDING_SUPER_NODE: u8 = 58;
    pub(crate) const GLOBAL_VARIABLE_AND_WRITE_NODE: u8 = 59;
    pub(crate) const GLOBAL_VARIABLE_OPERATOR_WRITE_NODE: u8 = 60;
    pub(crate) const GLOBAL_VARIABLE_OR_WRITE_NODE: u8 = 61;
    pub(crate) const GLOBAL_VARIABLE_READ_NODE: u8 = 62;
    pub(crate) const GLOBAL_VARIABLE_TARGET_NODE: u8 = 63;
    pub(crate) const GLOBAL_VARIABLE_WRITE_NODE: u8 = 64;
    pub(crate) const HASH_NODE: u8 = 65;
    pub(crate) const HASH_PATTERN_NODE: u8 = 66;
    pub(crate) const IF_NODE: u8 = 67;
    pub(crate) const IMAGINARY_NODE: u8 = 68;
    pub(crate) const IMPLICIT_NODE: u8 = 69;
    pub(crate) const IMPLICIT_REST_NODE: u8 = 70;
    pub(crate) const IN_NODE: u8 = 71;
    pub(crate) const INDEX_AND_WRITE_NODE: u8 = 72;
    pub(crate) const INDEX_OPERATOR_WRITE_NODE: u8 = 73;
    pub(crate) const INDEX_OR_WRITE_NODE: u8 = 74;
    pub(crate) const INDEX_TARGET_NODE: u8 = 75;
    pub(crate) const INSTANCE_VARIABLE_AND_WRITE_NODE: u8 = 76;
    pub(crate) const INSTANCE_VARIABLE_OPERATOR_WRITE_NODE: u8 = 77;
    pub(crate) const INSTANCE_VARIABLE_OR_WRITE_NODE: u8 = 78;
    pub(crate) const INSTANCE_VARIABLE_READ_NODE: u8 = 79;
    pub(crate) const INSTANCE_VARIABLE_TARGET_NODE: u8 = 80;
    pub(crate) const INSTANCE_VARIABLE_WRITE_NODE: u8 = 81;
    pub(crate) const INTEGER_NODE: u8 = 82;
    pub(crate) const INTERPOLATED_MATCH_LAST_LINE_NODE: u8 = 83;
    pub(crate) const INTERPOLATED_REGULAR_EXPRESSION_NODE: u8 = 84;
    pub(crate) const INTERPOLATED_STRING_NODE: u8 = 85;
    pub(crate) const INTERPOLATED_SYMBOL_NODE: u8 = 86;
    pub(crate) const INTERPOLATED_XSTRING_NODE: u8 = 87;
    pub(crate) const IT_LOCAL_VARIABLE_READ_NODE: u8 = 88;
    pub(crate) const IT_PARAMETERS_NODE: u8 = 89;
    pub(crate) const KEYWORD_HASH_NODE: u8 = 90;
    pub(crate) const KEYWORD_REST_PARAMETER_NODE: u8 = 91;
    pub(crate) const LAMBDA_NODE: u8 = 92;
    pub(crate) const LOCAL_VARIABLE_AND_WRITE_NODE: u8 = 93;
    pub(crate) const LOCAL_VARIABLE_OPERATOR_WRITE_NODE: u8 = 94;
    pub(crate) const LOCAL_VARIABLE_OR_WRITE_NODE: u8 = 95;
    pub(crate) const LOCAL_VARIABLE_READ_NODE: u8 = 96;
    pub(crate) const LOCAL_VARIABLE_TARGET_NODE: u8 = 97;
    pub(crate) const LOCAL_VARIABLE_WRITE_NODE: u8 = 98;
    pub(crate) const MATCH_LAST_LINE_NODE: u8 = 99;
    pub(crate) const MATCH_PREDICATE_NODE: u8 = 100;
    pub(crate) const MATCH_REQUIRED_NODE: u8 = 101;
    pub(crate) const MATCH_WRITE_NODE: u8 = 102;
    pub(crate) const MISSING_NODE: u8 = 103;
    pub(crate) const MODULE_NODE: u8 = 104;
    pub(crate) const MULTI_TARGET_NODE: u8 = 105;
    pub(crate) const MULTI_WRITE_NODE: u8 = 106;
    pub(crate) const NEXT_NODE: u8 = 107;
    pub(crate) const NIL_NODE: u8 = 108;
    pub(crate) const NO_KEYWORDS_PARAMETER_NODE: u8 = 109;
    pub(crate) const NUMBERED_PARAMETERS_NODE: u8 = 110;
    pub(crate) const NUMBERED_REFERENCE_READ_NODE: u8 = 111;
    pub(crate) const OPTIONAL_KEYWORD_PARAMETER_NODE: u8 = 112;
    pub(crate) const OPTIONAL_PARAMETER_NODE: u8 = 113;
    pub(crate) const OR_NODE: u8 = 114;
    pub(crate) const PARAMETERS_NODE: u8 = 115;
    pub(crate) const PARENTHESES_NODE: u8 = 116;
    pub(crate) const PINNED_EXPRESSION_NODE: u8 = 117;
    pub(crate) const PINNED_VARIABLE_NODE: u8 = 118;
    pub(crate) const POST_EXECUTION_NODE: u8 = 119;
    pub(crate) const PRE_EXECUTION_NODE: u8 = 120;
    pub(crate) const PROGRAM_NODE: u8 = 121;
    pub(crate) const RANGE_NODE: u8 = 122;
    pub(crate) const RATIONAL_NODE: u8 = 123;
    pub(crate) const REDO_NODE: u8 = 124;
    pub(crate) const REGULAR_EXPRESSION_NODE: u8 = 125;
    pub(crate) const REQUIRED_KEYWORD_PARAMETER_NODE: u8 = 126;
    pub(crate) const REQUIRED_PARAMETER_NODE: u8 = 127;
    pub(crate) const RESCUE_MODIFIER_NODE: u8 = 128;
    pub(crate) const RESCUE_NODE: u8 = 129;
    pub(crate) const REST_PARAMETER_NODE: u8 = 130;
    pub(crate) const RETRY_NODE: u8 = 131;
    pub(crate) const RETURN_NODE: u8 = 132;
    pub(crate) const SELF_NODE: u8 = 133;
    pub(crate) const SHAREABLE_CONSTANT_NODE: u8 = 134;
    pub(crate) const SINGLETON_CLASS_NODE: u8 = 135;
    pub(crate) const SOURCE_ENCODING_NODE: u8 = 136;
    pub(crate) const SOURCE_FILE_NODE: u8 = 137;
    pub(crate) const SOURCE_LINE_NODE: u8 = 138;
    pub(crate) const SPLAT_NODE: u8 = 139;
    pub(crate) const STATEMENTS_NODE: u8 = 140;
    pub(crate) const STRING_NODE: u8 = 141;
    pub(crate) const SUPER_NODE: u8 = 142;
    pub(crate) const SYMBOL_NODE: u8 = 143;
    pub(crate) const TRUE_NODE: u8 = 144;
    pub(crate) const UNDEF_NODE: u8 = 145;
    pub(crate) const UNLESS_NODE: u8 = 146;
    pub(crate) const UNTIL_NODE: u8 = 147;
    pub(crate) const WHEN_NODE: u8 = 148;
    pub(crate) const WHILE_NODE: u8 = 149;
    pub(crate) const XSTRING_NODE: u8 = 150;
    pub(crate) const YIELD_NODE: u8 = 151;
}

pub(crate) mod alias_global_variable_node {
    pub(crate) const NEW_NAME: usize = 0;
    pub(crate) const OLD_NAME: usize = 1;
    pub(crate) const KEYWORD_LOC: usize = 2;
}
pub(crate) mod alias_method_node {
    pub(crate) const NEW_NAME: usize = 0;
    pub(crate) const OLD_NAME: usize = 1;
    pub(crate) const KEYWORD_LOC: usize = 2;
}
pub(crate) mod alternation_pattern_node {
    pub(crate) const LEFT: usize = 0;
    pub(crate) const RIGHT: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod and_node {
    pub(crate) const LEFT: usize = 0;
    pub(crate) const RIGHT: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod arguments_node {
    pub(crate) const ARGUMENTS: usize = 0;
}
pub(crate) mod array_node {
    pub(crate) const ELEMENTS: usize = 0;
    pub(crate) const OPENING_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod array_pattern_node {
    pub(crate) const CONSTANT: usize = 0;
    pub(crate) const REQUIREDS: usize = 1;
    pub(crate) const REST: usize = 2;
    pub(crate) const POSTS: usize = 3;
    pub(crate) const OPENING_LOC: usize = 4;
    pub(crate) const CLOSING_LOC: usize = 5;
}
pub(crate) mod assoc_node {
    pub(crate) const KEY: usize = 0;
    pub(crate) const VALUE: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod assoc_splat_node {
    pub(crate) const VALUE: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
}
pub(crate) mod back_reference_read_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod begin_node {
    pub(crate) const BEGIN_KEYWORD_LOC: usize = 0;
    pub(crate) const STATEMENTS: usize = 1;
    pub(crate) const RESCUE_CLAUSE: usize = 2;
    pub(crate) const ELSE_CLAUSE: usize = 3;
    pub(crate) const ENSURE_CLAUSE: usize = 4;
    pub(crate) const END_KEYWORD_LOC: usize = 5;
}
pub(crate) mod block_argument_node {
    pub(crate) const EXPRESSION: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
}
pub(crate) mod block_local_variable_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod block_node {
    pub(crate) const LOCALS: usize = 0;
    pub(crate) const PARAMETERS: usize = 1;
    pub(crate) const BODY: usize = 2;
    pub(crate) const OPENING_LOC: usize = 3;
    pub(crate) const CLOSING_LOC: usize = 4;
}
pub(crate) mod block_parameter_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod block_parameters_node {
    pub(crate) const PARAMETERS: usize = 0;
    pub(crate) const LOCALS: usize = 1;
    pub(crate) const OPENING_LOC: usize = 2;
    pub(crate) const CLOSING_LOC: usize = 3;
}
pub(crate) mod break_node {
    pub(crate) const ARGUMENTS: usize = 0;
    pub(crate) const KEYWORD_LOC: usize = 1;
}
pub(crate) mod call_and_write_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const MESSAGE_LOC: usize = 2;
    pub(crate) const READ_NAME: usize = 3;
    pub(crate) const WRITE_NAME: usize = 4;
    pub(crate) const OPERATOR_LOC: usize = 5;
    pub(crate) const VALUE: usize = 6;
}
pub(crate) mod call_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const NAME: usize = 2;
    pub(crate) const MESSAGE_LOC: usize = 3;
    pub(crate) const OPENING_LOC: usize = 4;
    pub(crate) const ARGUMENTS: usize = 5;
    pub(crate) const CLOSING_LOC: usize = 6;
    pub(crate) const EQUAL_LOC: usize = 7;
    pub(crate) const BLOCK: usize = 8;
}
pub(crate) mod call_operator_write_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const MESSAGE_LOC: usize = 2;
    pub(crate) const READ_NAME: usize = 3;
    pub(crate) const WRITE_NAME: usize = 4;
    pub(crate) const BINARY_OPERATOR: usize = 5;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 6;
    pub(crate) const VALUE: usize = 7;
}
pub(crate) mod call_or_write_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const MESSAGE_LOC: usize = 2;
    pub(crate) const READ_NAME: usize = 3;
    pub(crate) const WRITE_NAME: usize = 4;
    pub(crate) const OPERATOR_LOC: usize = 5;
    pub(crate) const VALUE: usize = 6;
}
pub(crate) mod call_target_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const NAME: usize = 2;
    pub(crate) const MESSAGE_LOC: usize = 3;
}
pub(crate) mod capture_pattern_node {
    pub(crate) const VALUE: usize = 0;
    pub(crate) const TARGET: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod case_match_node {
    pub(crate) const PREDICATE: usize = 0;
    pub(crate) const CONDITIONS: usize = 1;
    pub(crate) const ELSE_CLAUSE: usize = 2;
    pub(crate) const CASE_KEYWORD_LOC: usize = 3;
    pub(crate) const END_KEYWORD_LOC: usize = 4;
}
pub(crate) mod case_node {
    pub(crate) const PREDICATE: usize = 0;
    pub(crate) const CONDITIONS: usize = 1;
    pub(crate) const ELSE_CLAUSE: usize = 2;
    pub(crate) const CASE_KEYWORD_LOC: usize = 3;
    pub(crate) const END_KEYWORD_LOC: usize = 4;
}
pub(crate) mod class_node {
    pub(crate) const LOCALS: usize = 0;
    pub(crate) const CLASS_KEYWORD_LOC: usize = 1;
    pub(crate) const CONSTANT_PATH: usize = 2;
    pub(crate) const INHERITANCE_OPERATOR_LOC: usize = 3;
    pub(crate) const SUPERCLASS: usize = 4;
    pub(crate) const BODY: usize = 5;
    pub(crate) const END_KEYWORD_LOC: usize = 6;
    pub(crate) const NAME: usize = 7;
}
pub(crate) mod class_variable_and_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod class_variable_operator_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
    pub(crate) const BINARY_OPERATOR: usize = 4;
}
pub(crate) mod class_variable_or_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod class_variable_read_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod class_variable_target_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod class_variable_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const OPERATOR_LOC: usize = 3;
}
pub(crate) mod constant_and_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod constant_operator_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
    pub(crate) const BINARY_OPERATOR: usize = 4;
}
pub(crate) mod constant_or_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod constant_path_and_write_node {
    pub(crate) const TARGET: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
}
pub(crate) mod constant_path_node {
    pub(crate) const PARENT: usize = 0;
    pub(crate) const NAME: usize = 1;
    pub(crate) const DELIMITER_LOC: usize = 2;
    pub(crate) const NAME_LOC: usize = 3;
}
pub(crate) mod constant_path_operator_write_node {
    pub(crate) const TARGET: usize = 0;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const BINARY_OPERATOR: usize = 3;
}
pub(crate) mod constant_path_or_write_node {
    pub(crate) const TARGET: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
}
pub(crate) mod constant_path_target_node {
    pub(crate) const PARENT: usize = 0;
    pub(crate) const NAME: usize = 1;
    pub(crate) const DELIMITER_LOC: usize = 2;
    pub(crate) const NAME_LOC: usize = 3;
}
pub(crate) mod constant_path_write_node {
    pub(crate) const TARGET: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
}
pub(crate) mod constant_read_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod constant_target_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod constant_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const OPERATOR_LOC: usize = 3;
}
pub(crate) mod def_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const RECEIVER: usize = 2;
    pub(crate) const PARAMETERS: usize = 3;
    pub(crate) const BODY: usize = 4;
    pub(crate) const LOCALS: usize = 5;
    pub(crate) const DEF_KEYWORD_LOC: usize = 6;
    pub(crate) const OPERATOR_LOC: usize = 7;
    pub(crate) const LPAREN_LOC: usize = 8;
    pub(crate) const RPAREN_LOC: usize = 9;
    pub(crate) const EQUAL_LOC: usize = 10;
    pub(crate) const END_KEYWORD_LOC: usize = 11;
}
pub(crate) mod defined_node {
    pub(crate) const LPAREN_LOC: usize = 0;
    pub(crate) const VALUE: usize = 1;
    pub(crate) const RPAREN_LOC: usize = 2;
    pub(crate) const KEYWORD_LOC: usize = 3;
}
pub(crate) mod else_node {
    pub(crate) const ELSE_KEYWORD_LOC: usize = 0;
    pub(crate) const STATEMENTS: usize = 1;
    pub(crate) const END_KEYWORD_LOC: usize = 2;
}
pub(crate) mod embedded_statements_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const STATEMENTS: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod embedded_variable_node {
    pub(crate) const OPERATOR_LOC: usize = 0;
    pub(crate) const VARIABLE: usize = 1;
}
pub(crate) mod ensure_node {
    pub(crate) const ENSURE_KEYWORD_LOC: usize = 0;
    pub(crate) const STATEMENTS: usize = 1;
    pub(crate) const END_KEYWORD_LOC: usize = 2;
}
pub(crate) mod find_pattern_node {
    pub(crate) const CONSTANT: usize = 0;
    pub(crate) const LEFT: usize = 1;
    pub(crate) const REQUIREDS: usize = 2;
    pub(crate) const RIGHT: usize = 3;
    pub(crate) const OPENING_LOC: usize = 4;
    pub(crate) const CLOSING_LOC: usize = 5;
}
pub(crate) mod flip_flop_node {
    pub(crate) const LEFT: usize = 0;
    pub(crate) const RIGHT: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod float_node {
    pub(crate) const VALUE: usize = 0;
}
pub(crate) mod for_node {
    pub(crate) const INDEX: usize = 0;
    pub(crate) const COLLECTION: usize = 1;
    pub(crate) const STATEMENTS: usize = 2;
    pub(crate) const FOR_KEYWORD_LOC: usize = 3;
    pub(crate) const IN_KEYWORD_LOC: usize = 4;
    pub(crate) const DO_KEYWORD_LOC: usize = 5;
    pub(crate) const END_KEYWORD_LOC: usize = 6;
}
pub(crate) mod forwarding_super_node {
    pub(crate) const BLOCK: usize = 0;
}
pub(crate) mod global_variable_and_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod global_variable_operator_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
    pub(crate) const BINARY_OPERATOR: usize = 4;
}
pub(crate) mod global_variable_or_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod global_variable_read_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod global_variable_target_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod global_variable_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const OPERATOR_LOC: usize = 3;
}
pub(crate) mod hash_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const ELEMENTS: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod hash_pattern_node {
    pub(crate) const CONSTANT: usize = 0;
    pub(crate) const ELEMENTS: usize = 1;
    pub(crate) const REST: usize = 2;
    pub(crate) const OPENING_LOC: usize = 3;
    pub(crate) const CLOSING_LOC: usize = 4;
}
pub(crate) mod if_node {
    pub(crate) const IF_KEYWORD_LOC: usize = 0;
    pub(crate) const PREDICATE: usize = 1;
    pub(crate) const THEN_KEYWORD_LOC: usize = 2;
    pub(crate) const STATEMENTS: usize = 3;
    pub(crate) const SUBSEQUENT: usize = 4;
    pub(crate) const END_KEYWORD_LOC: usize = 5;
}
pub(crate) mod imaginary_node {
    pub(crate) const NUMERIC: usize = 0;
}
pub(crate) mod implicit_node {
    pub(crate) const VALUE: usize = 0;
}
pub(crate) mod in_node {
    pub(crate) const PATTERN: usize = 0;
    pub(crate) const STATEMENTS: usize = 1;
    pub(crate) const IN_LOC: usize = 2;
    pub(crate) const THEN_LOC: usize = 3;
}
pub(crate) mod index_and_write_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const OPENING_LOC: usize = 2;
    pub(crate) const ARGUMENTS: usize = 3;
    pub(crate) const CLOSING_LOC: usize = 4;
    pub(crate) const BLOCK: usize = 5;
    pub(crate) const OPERATOR_LOC: usize = 6;
    pub(crate) const VALUE: usize = 7;
}
pub(crate) mod index_operator_write_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const OPENING_LOC: usize = 2;
    pub(crate) const ARGUMENTS: usize = 3;
    pub(crate) const CLOSING_LOC: usize = 4;
    pub(crate) const BLOCK: usize = 5;
    pub(crate) const BINARY_OPERATOR: usize = 6;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 7;
    pub(crate) const VALUE: usize = 8;
}
pub(crate) mod index_or_write_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const CALL_OPERATOR_LOC: usize = 1;
    pub(crate) const OPENING_LOC: usize = 2;
    pub(crate) const ARGUMENTS: usize = 3;
    pub(crate) const CLOSING_LOC: usize = 4;
    pub(crate) const BLOCK: usize = 5;
    pub(crate) const OPERATOR_LOC: usize = 6;
    pub(crate) const VALUE: usize = 7;
}
pub(crate) mod index_target_node {
    pub(crate) const RECEIVER: usize = 0;
    pub(crate) const OPENING_LOC: usize = 1;
    pub(crate) const ARGUMENTS: usize = 2;
    pub(crate) const CLOSING_LOC: usize = 3;
    pub(crate) const BLOCK: usize = 4;
}
pub(crate) mod instance_variable_and_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod instance_variable_operator_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
    pub(crate) const BINARY_OPERATOR: usize = 4;
}
pub(crate) mod instance_variable_or_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod instance_variable_read_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod instance_variable_target_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod instance_variable_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const OPERATOR_LOC: usize = 3;
}
pub(crate) mod integer_node {
    pub(crate) const VALUE: usize = 0;
}
pub(crate) mod interpolated_match_last_line_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const PARTS: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod interpolated_regular_expression_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const PARTS: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod interpolated_string_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const PARTS: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod interpolated_symbol_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const PARTS: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod interpolated_xstring_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const PARTS: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod keyword_hash_node {
    pub(crate) const ELEMENTS: usize = 0;
}
pub(crate) mod keyword_rest_parameter_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod lambda_node {
    pub(crate) const LOCALS: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
    pub(crate) const OPENING_LOC: usize = 2;
    pub(crate) const CLOSING_LOC: usize = 3;
    pub(crate) const PARAMETERS: usize = 4;
    pub(crate) const BODY: usize = 5;
}
pub(crate) mod local_variable_and_write_node {
    pub(crate) const NAME_LOC: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const NAME: usize = 3;
    pub(crate) const DEPTH: usize = 4;
}
pub(crate) mod local_variable_operator_write_node {
    pub(crate) const NAME_LOC: usize = 0;
    pub(crate) const BINARY_OPERATOR_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const NAME: usize = 3;
    pub(crate) const BINARY_OPERATOR: usize = 4;
    pub(crate) const DEPTH: usize = 5;
}
pub(crate) mod local_variable_or_write_node {
    pub(crate) const NAME_LOC: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
    pub(crate) const NAME: usize = 3;
    pub(crate) const DEPTH: usize = 4;
}
pub(crate) mod local_variable_read_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const DEPTH: usize = 1;
}
pub(crate) mod local_variable_target_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const DEPTH: usize = 1;
}
pub(crate) mod local_variable_write_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const DEPTH: usize = 1;
    pub(crate) const NAME_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
    pub(crate) const OPERATOR_LOC: usize = 4;
}
pub(crate) mod match_last_line_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const CONTENT_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
    pub(crate) const UNESCAPED: usize = 3;
}
pub(crate) mod match_predicate_node {
    pub(crate) const VALUE: usize = 0;
    pub(crate) const PATTERN: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod match_required_node {
    pub(crate) const VALUE: usize = 0;
    pub(crate) const PATTERN: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod match_write_node {
    pub(crate) const CALL: usize = 0;
    pub(crate) const TARGETS: usize = 1;
}
pub(crate) mod module_node {
    pub(crate) const LOCALS: usize = 0;
    pub(crate) const MODULE_KEYWORD_LOC: usize = 1;
    pub(crate) const CONSTANT_PATH: usize = 2;
    pub(crate) const BODY: usize = 3;
    pub(crate) const END_KEYWORD_LOC: usize = 4;
    pub(crate) const NAME: usize = 5;
}
pub(crate) mod multi_target_node {
    pub(crate) const LEFTS: usize = 0;
    pub(crate) const REST: usize = 1;
    pub(crate) const RIGHTS: usize = 2;
    pub(crate) const LPAREN_LOC: usize = 3;
    pub(crate) const RPAREN_LOC: usize = 4;
}
pub(crate) mod multi_write_node {
    pub(crate) const LEFTS: usize = 0;
    pub(crate) const REST: usize = 1;
    pub(crate) const RIGHTS: usize = 2;
    pub(crate) const LPAREN_LOC: usize = 3;
    pub(crate) const RPAREN_LOC: usize = 4;
    pub(crate) const OPERATOR_LOC: usize = 5;
    pub(crate) const VALUE: usize = 6;
}
pub(crate) mod next_node {
    pub(crate) const ARGUMENTS: usize = 0;
    pub(crate) const KEYWORD_LOC: usize = 1;
}
pub(crate) mod no_keywords_parameter_node {
    pub(crate) const OPERATOR_LOC: usize = 0;
    pub(crate) const KEYWORD_LOC: usize = 1;
}
pub(crate) mod numbered_parameters_node {
    pub(crate) const MAXIMUM: usize = 0;
}
pub(crate) mod numbered_reference_read_node {
    pub(crate) const NUMBER: usize = 0;
}
pub(crate) mod optional_keyword_parameter_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const VALUE: usize = 2;
}
pub(crate) mod optional_parameter_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const VALUE: usize = 3;
}
pub(crate) mod or_node {
    pub(crate) const LEFT: usize = 0;
    pub(crate) const RIGHT: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod parameters_node {
    pub(crate) const REQUIREDS: usize = 0;
    pub(crate) const OPTIONALS: usize = 1;
    pub(crate) const REST: usize = 2;
    pub(crate) const POSTS: usize = 3;
    pub(crate) const KEYWORDS: usize = 4;
    pub(crate) const KEYWORD_REST: usize = 5;
    pub(crate) const BLOCK: usize = 6;
}
pub(crate) mod parentheses_node {
    pub(crate) const BODY: usize = 0;
    pub(crate) const OPENING_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
}
pub(crate) mod pinned_expression_node {
    pub(crate) const EXPRESSION: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
    pub(crate) const LPAREN_LOC: usize = 2;
    pub(crate) const RPAREN_LOC: usize = 3;
}
pub(crate) mod pinned_variable_node {
    pub(crate) const VARIABLE: usize = 0;
    pub(crate) const OPERATOR_LOC: usize = 1;
}
pub(crate) mod post_execution_node {
    pub(crate) const STATEMENTS: usize = 0;
    pub(crate) const KEYWORD_LOC: usize = 1;
    pub(crate) const OPENING_LOC: usize = 2;
    pub(crate) const CLOSING_LOC: usize = 3;
}
pub(crate) mod pre_execution_node {
    pub(crate) const STATEMENTS: usize = 0;
    pub(crate) const KEYWORD_LOC: usize = 1;
    pub(crate) const OPENING_LOC: usize = 2;
    pub(crate) const CLOSING_LOC: usize = 3;
}
pub(crate) mod program_node {
    pub(crate) const LOCALS: usize = 0;
    pub(crate) const STATEMENTS: usize = 1;
}
pub(crate) mod range_node {
    pub(crate) const LEFT: usize = 0;
    pub(crate) const RIGHT: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod rational_node {
    pub(crate) const NUMERATOR: usize = 0;
    pub(crate) const DENOMINATOR: usize = 1;
}
pub(crate) mod regular_expression_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const CONTENT_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
    pub(crate) const UNESCAPED: usize = 3;
}
pub(crate) mod required_keyword_parameter_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
}
pub(crate) mod required_parameter_node {
    pub(crate) const NAME: usize = 0;
}
pub(crate) mod rescue_modifier_node {
    pub(crate) const EXPRESSION: usize = 0;
    pub(crate) const KEYWORD_LOC: usize = 1;
    pub(crate) const RESCUE_EXPRESSION: usize = 2;
}
pub(crate) mod rescue_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const EXCEPTIONS: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const REFERENCE: usize = 3;
    pub(crate) const THEN_KEYWORD_LOC: usize = 4;
    pub(crate) const STATEMENTS: usize = 5;
    pub(crate) const SUBSEQUENT: usize = 6;
}
pub(crate) mod rest_parameter_node {
    pub(crate) const NAME: usize = 0;
    pub(crate) const NAME_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
}
pub(crate) mod return_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const ARGUMENTS: usize = 1;
}
pub(crate) mod shareable_constant_node {
    pub(crate) const WRITE: usize = 0;
}
pub(crate) mod singleton_class_node {
    pub(crate) const LOCALS: usize = 0;
    pub(crate) const CLASS_KEYWORD_LOC: usize = 1;
    pub(crate) const OPERATOR_LOC: usize = 2;
    pub(crate) const EXPRESSION: usize = 3;
    pub(crate) const BODY: usize = 4;
    pub(crate) const END_KEYWORD_LOC: usize = 5;
}
pub(crate) mod source_file_node {
    pub(crate) const FILEPATH: usize = 0;
}
pub(crate) mod splat_node {
    pub(crate) const OPERATOR_LOC: usize = 0;
    pub(crate) const EXPRESSION: usize = 1;
}
pub(crate) mod statements_node {
    pub(crate) const BODY: usize = 0;
}
pub(crate) mod string_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const CONTENT_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
    pub(crate) const UNESCAPED: usize = 3;
}
pub(crate) mod super_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const LPAREN_LOC: usize = 1;
    pub(crate) const ARGUMENTS: usize = 2;
    pub(crate) const RPAREN_LOC: usize = 3;
    pub(crate) const BLOCK: usize = 4;
}
pub(crate) mod symbol_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const VALUE_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
    pub(crate) const UNESCAPED: usize = 3;
}
pub(crate) mod undef_node {
    pub(crate) const NAMES: usize = 0;
    pub(crate) const KEYWORD_LOC: usize = 1;
}
pub(crate) mod unless_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const PREDICATE: usize = 1;
    pub(crate) const THEN_KEYWORD_LOC: usize = 2;
    pub(crate) const STATEMENTS: usize = 3;
    pub(crate) const ELSE_CLAUSE: usize = 4;
    pub(crate) const END_KEYWORD_LOC: usize = 5;
}
pub(crate) mod until_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const DO_KEYWORD_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
    pub(crate) const PREDICATE: usize = 3;
    pub(crate) const STATEMENTS: usize = 4;
}
pub(crate) mod when_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const CONDITIONS: usize = 1;
    pub(crate) const THEN_KEYWORD_LOC: usize = 2;
    pub(crate) const STATEMENTS: usize = 3;
}
pub(crate) mod while_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const DO_KEYWORD_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
    pub(crate) const PREDICATE: usize = 3;
    pub(crate) const STATEMENTS: usize = 4;
}
pub(crate) mod xstring_node {
    pub(crate) const OPENING_LOC: usize = 0;
    pub(crate) const CONTENT_LOC: usize = 1;
    pub(crate) const CLOSING_LOC: usize = 2;
    pub(crate) const UNESCAPED: usize = 3;
}
pub(crate) mod yield_node {
    pub(crate) const KEYWORD_LOC: usize = 0;
    pub(crate) const LPAREN_LOC: usize = 1;
    pub(crate) const ARGUMENTS: usize = 2;
    pub(crate) const RPAREN_LOC: usize = 3;
}
